### ISSUE TITLE
SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#731] opened 2020-07-24 13:36 UTC
Hi!

This error happens the first time I load the app when the database is created for the first time, but after that, the database seems to work fine even with this error.

It happens BEFORE the tables are created because it is set as lazy and the error happens before.
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)
#0      new Database.open (package:moor_ffi/src/impl/database.dart:65:7)
#1      new Database.openFile (package:moor_ffi/src/impl/database.dart:37:52)
#2      _VmDelegate.open (package:moor_ffi/src/vm_database.dart:39:22)
#3      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:244:22)
<asynchronous suspension>
#4      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart)
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
#6      DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:238:25)
#7      LazyDatabase.ensureOpen.<anonymous closure> (package:moor/src/utils/lazy_database.dart:43:49)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._propagateToListeners (dart:async/future_impl.dart:609:9)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#16     _rootRun (dart:async/zone.dart:1184:13)
#17     _CustomZone.run (dart:async/zone.dart:1077:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

Any clue why this happens or how to debug it?

**Comment by simolus3** [comment] 2020-07-24 14:15
Thanks for the report! Which Flutter and `moor_ffi` version are you using? Does this happen on release builds only or on debug builds too? If you're on iOS, which iOS version are you using?

**Comment by apoleo88** [comment] 2020-07-24 15:50
Thanks for your attention!

```
dependencies:
  moor: 
  moor_ffi: 0.5.0
dev_dependencies:
  moor_generator: 
```
I am testing it only on an Android emulated device, the error shows both on release and debug.

At first, I thought it was because I added some code in the MyDatabase constructor but I removed it and rebuilt it, but the error is still there.

**Comment by simolus3** [comment] 2020-07-25 07:43
You could try upgrading `moor_ffi` to `^0.7.0`, but I doubt that this will change much.

If you look at the built apk, does it contain `libsqlite3.so` in its libs?

**Comment by apoleo88** [comment] 2020-07-26 17:04
I am not using 0.7.0 because of https://github.com/simolus3/moor/issues/581 , but I tried and the error persists.


I am not sure how to check this:
> If you look at the built apk, does it contain `libsqlite3.so` in its libs?

**Comment by HrX03** [comment] 2020-07-26 18:34
i am getting the same error, moor_ffi 0.7.0, device is pixel 3a emulator with api 23, i can't get the database to work at all, i always get bad parameter or other API misues (error 21), checked debug apk and libsqlite3 is present

**Comment by simolus3** [comment] 2020-07-27 13:36
Thanks, I'll try to reproduce this, Which ABI did you use on the emulator?

**Comment by GP4cK** [comment] 2020-08-13 04:00
Same error for me with:
moor: ^3.3.1
sqlite3_flutter_libs: ^0.2.0

Phone: OnePlus One
Model: A0001
Android 6.0.1

I can't reproduce with an emulator though :/

**Comment by GP4cK** [comment] 2020-08-13 10:20
@simolus3 I'd be happy to help resolve the issue but I need some guidance. I've tried:
1. in the root of the project, run `flutter build apk`
2. open Android Studio and import the `android/` folder
3. debug the app and reproduce the issue
I see the error message in `Logcat` but there is nothing that tells me where it comes from.
I've looked at the code in `Project > sqflite/java/com.tekartik.sqflite/SqflitePlugin.java` but couldn't find anything...
![image](https://user-images.githubusercontent.com/2680243/90123441-6738e600-dd91-11ea-9123-da3a83ebf438.png)

**Comment by simolus3** [comment] 2020-08-13 13:32
If you use the `moor/ffi.dart` library, we won't use `sqflite` at all (you can switch to an `sqflite`-based implementation by using `moor_flutter`). Instead, we load `libsqlite3.so` and use `dart:ffi` to call sqlite3's C-api. 
Can you try to print the `sqlite3` version used in your app? You can use

```dart
import 'package:sqlite3/sqlite3.dart';

void main() {
  print('Using sqlite3 ${sqlite3.version}');
  // Rest of your main method...
```

If it prints something older than 3.32.3, maybe there's an issue in the build scripts that I could take a look at.

**Comment by GP4cK** [comment] 2020-08-14 00:23
It says `Using sqlite3 Version(libVersion: 3.32.3, sourceId: 2020-06-18 14:00:33 7ebdfa80be8e8e73324b8d66b3460222eb74c7e9dfd655b48d6ca7e1933cc8fd, number: 3032003)`

**Comment by simolus3** [comment] 2020-08-14 07:38
Thanks! That means it's using the latest sqlite3 version. You could try to set a breakpoint [here](https://github.com/simolus3/sqlite3.dart/blob/master/sqlite3/lib/src/impl/database.dart#L28) to debug the call causing the exception. I don't think there's anything wrong with `flags`, but maybe it's complaining about the set `filename`?

**Comment by davidmartos96** [comment] 2020-08-14 07:45
@apoleo88 For what is worth, I had the API misuse error when opening the database before. The error was that the folder where I wanted to place the database didn't exist. 
I would check that as Simon suggests.
I usually call the `Directory(folder).create(recursive: true)` for safety before opening.

**Comment by GP4cK** [comment] 2020-08-14 09:52
After removing `sqflite` from the `pubspec.yaml`, I can't reproduce the issue anymore... :)

**Comment by apoleo88** [comment] 2020-08-14 18:35
> 
> 
> @apoleo88 For what is worth, I had the API misuse error when opening the database before. The error was that the folder where I wanted to place the database didn't exist.
> I would check that as Simon suggests.
> I usually call the `Directory(folder).create(recursive: true)` for safety before opening.

Good catch, I was calling it, but asynchronously. 
Solved for me.

**Comment by davidmartos96** [comment] 2020-08-14 19:04
@simolus3 Do you think moor should automatically create the directories when opening the database? The API misuse error from native sqlite may be confusing.

**Comment by simolus3** [comment] 2020-08-14 20:03
Yes, I agree - thanks for the suggestion! I added this in ffc01e4516ef489f0bb5bdfce8332cd45374e94e. Since manually creating the directory seems to fix the problem, I'll close this issue.

**Closed by simolus3** 2020-08-14 20:03 UTC

**Comment by fernando-s97** [comment] 2020-12-22 00:24
I'm facing the same issue on Windows.

**Environment**

- moor: ^3.4.0
- sqlite3_flutter_libs: ^0.3.0
- path_provider: ^1.6.24
- path: ^1.7.0
- build_runner: ^1.10.11
- moor_generator: ^3.4.0
- sqlite3.dll in project path - "Using sqlite3 Version(libVersion: 3.34.0, sourceId: 2020-12-01 16:14:00 a26b6597e3ae272231b96f9982c3bcc17ddec2f2b6eb4df06a224b91089fed5b, number: 3034000)"

**Flutter doctor**

[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 10.0.19613.1005],
    locale pt-BR)
    • Flutter version 1.26.0-1.0.pre at C:\tools\flutter
    • Framework revision 63062a6443 (8 days ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\fosan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version
      10.0.19613.1005]

• No issues found!

**db path**

C:\Users\fosan\Documents\db.sqlite

**Error**
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)
#0      new DatabaseImpl.open (package:sqlite3/src/impl/database.dart:53:7)
#1      Sqlite3.open (package:sqlite3/src/api/sqlite3.dart:51:25)
#2      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:126:21)
#3      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:255:22)
<asynchronous suspension>
#4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34:18)
<asynchronous suspension>
#5      QueryEngine.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart)
<asynchronous suspension>

**Comment by fernando-s97** [comment] 2020-12-23 03:46
My problems were two things, both related to write permission. The first problem was that my application project was under the desktop folder and the second one was that the `await getApplicationDocumentsDirectory();` returned the `Documents ` folder. 

What solved for me was to create the database in the same folder of the project and to move to project folder itself to C:\StudioProjects

**Comment by yiky84119** [comment] 2020-12-25 02:29
I'm facing the same issue on Windows. when start on the PC startup

**Comment by BenVercammen** [comment] 2021-05-21 09:00
> I'm facing the same issue on Windows. when start on the PC startup

As @fernando-s97 mentioned, make sure that your flutter exe process is allowed to access and read/write files in the "C:\Documents" folder.

When using the snippet below, pay attention to the `getApplicatoinDocumentsDirectory()`. 

```
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
  });
}
```

My Windows Defender (or however it is called) was blocking the "app or process" called `flutter_tester.exe` from my secured `C:\Documents\` folder (blocked by `Controlled folder access`).

Hope this helps.
