### ISSUE TITLE
DateTime conversion error

### ISSUE THREAD

**Issue by fabioda** [simolus3/moor#2635] opened 2023-09-24 13:25 UTC
Hello,
I'm just started using drift, and I encountered a bug when working with date time fields.
My table has several fields, including this.

`  DateTimeColumn get validFrom => dateTime().nullable().named('validFrom')();`

When I run a select statement i get the following error:

```
FormatException: Invalid radix-10 number (at character 2)
2023-09-24 12:47:12
 ^
```

In my sqlite table,  the column  is of type DATETIME.

Using TextColumn with a converter works, but I don't feel it's ideal.

Thanks.

**Comment by simolus3** [comment] 2023-09-24 19:30
>  Invalid radix-10 number

By default, drift expects date times to be stored as unix timestamps. You can [tell drift to store them as text instead though](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#datetime-options). Be aware that drift interprets datetimes without an explicit UTC offset (which would look like `2023-09-24 14:47:12+02:00`) as being in UTC, so if you intended the value to be in the local time zone, a [migration may be necessary](https://github.com/simolus3/drift/discussions/2630).

> In my sqlite table, the column is of type DATETIME.

Note that sqlite doesn't support a `DATETIME` type, writing `DATETIME` creates a numeric column as [explained here](https://sqlite.org/datatype3.html#determination_of_column_affinity). That doesn't mean much due to sqlite3's flexible typing scheme, but it's something to be aware of :D

I'll close this as working as intended, but if you more questions just let me know.

**Closed as not planned by simolus3** 2023-09-24 19:30 UTC
