### ISSUE TITLE
Background processing support for Flutter Web

### ISSUE THREAD

**Issue by julien100000** [simolus3/moor#1022] opened 2021-01-31 02:19 UTC
I am using Moor for my Flutter App on Android, IOS and Web.

You provided a good solution to use the same code for database for mobile devices and for web. Also you provide a way to execute the database stuff in the background using Isolates. This works really well, but sadly only for Android and iOS since in Web there are no Isolates.

I read that the current workaround for this is to use Web Workers (https://github.com/flutter/flutter/issues/33577). Maybe it is possible to integrate that into Moor.

**Comment by simolus3** [comment] 2021-01-31 09:08
Thanks for the idea! Unfortunately it's not really easy to use web workers in Dart right now. Something like `build_web_compilers` would only compile scripts in your package, so we can't just go and add a worker entrypoint in moor. You would have to write the worker yourself. With Flutter's compilation model it might be even worse since I think it can only compile one entrypoint at a time?

You can also use the `inWebWorker` parameter for `MoorWebStorage.indexedDb` to use moor inside a worker. With that, you'd still have to write the communication logic yourself though.
Currently, moor's isolate library serializes messages over a custom isolate rpc channel. We might be able to use the `stream_channel` library for that, which would make it easier to use a custom communication channel (like web workers) for a remote database.

Also, I think this is a duplicate of #468.

**Closed by simolus3** 2021-01-31 09:08 UTC
Labels: enhancement

**Comment by julien100000** [comment] 2021-01-31 15:52
Thanks for the reply, and sorry for the duplicate I did not saw the other issue.
Do you maybe have an example of how to write the communication logic if using inWebWorker forMoorWebStorage.indexedDb? Would be really nice since I do not have any idea on how to start.
Anyway thanks for your great libary :)

**Comment by simolus3** [comment] 2021-01-31 19:01
Thanks! Today, I added a new api to call remote databases over an arbitrary communication channel. I'm still playing around with that, but if everything works out as planned it could be pretty easy to use a web worker for moor. We might even be able to use a shared worker to synchronize stream queries across multiple tabs :)

I'll comment on the other issue once I have more details.

**Comment by julien100000** [comment] 2021-01-31 20:48
> but if everything works out as planned it could be pretty easy to use a web worker for moor

That would be awesome!
