### ISSUE TITLE
Syntax error near 'order' while executing moor generated sql

### ISSUE THREAD

**Issue by mdccxv** [simolus3/moor#700] opened 2020-07-14 13:03 UTC
Moor generated sql causes error `near "order": syntax error`

The sql itself is:
``CREATE TABLE IF NOT EXISTS audio_stream_db (event_id INTEGER NOT NULL, url VARCHAR NULL, name VARCHAR NULL, `order` INTEGER NOT NULL, PRIMARY KEY (event_id, order));
``

Maybe it has something to do with the fact that 'order' is a keyword in sqlite?
My local solution was just to call a field "position" instead of "order", but maybe it is something you'd want to address. Thanks for the great library.

**Comment by simolus3** [comment] 2020-07-14 14:32
Thanks for the report. As you said, the problem is that `order` is not escaped in the primary key clause. I think that issue should be fixed in the latest moor version (see also #661). Can you try to run `flutter pub upgrade` and check if that fixes the problem?

**Closed by simolus3** 2020-07-14 14:32 UTC

**Comment by mdccxv** [comment] 2020-07-16 15:25
> Thanks for the report. As you said, the problem is that `order` is not escaped in the primary key clause. I think that issue should be fixed in the latest moor version (see also #661). Can you try to run `flutter pub upgrade` and check if that fixes the problem?

New version after `flutter pub upgrade` resolves the issue indeed.
