### ISSUE TITLE
Stream has no data when table has many entries

### ISSUE THREAD

**Issue by Tiger3030** [simolus3/moor#897] opened 2020-10-28 19:41 UTC
I want to get the following data in a stream:
```
SELECT episodes.show_id, COUNT(*), MAX(history.watched_at), episodes.season_number, episodes.number
FROM history
LEFT JOIN episodes ON episodes.id = history.id
LEFT JOIN shows ON shows.id = episodes.show_id
LEFT JOIN seasons ON seasons.id = episodes.season_id
WHERE history.type = 'episode' AND shows.hidden_watched_at is null AND seasons.hidden_watched_at is null
GROUP BY episodes.show_id;
```

This is my code:
```
Stream<List<HistoryAdapter>> testStream() {
    final count = countAll();
    final lastWatched = history.watchedAt; //.max()
    final showId = episodes.showId;

    final historyQuery = (selectOnly(history)
      ..where(history.type.equals('episode') & isNull(shows.hiddenWatchedAt) & isNull(seasons.hiddenWatchedAt)))
        .join([
      leftOuterJoin(episodes, episodes.id.equalsExp(history.id)),
      leftOuterJoin(shows, shows.id.equalsExp(showId)),
      leftOuterJoin(seasons, seasons.id.equalsExp(episodes.seasonId))
    ])
      ..addColumns([count])
      ..addColumns([lastWatched])
      ..addColumns([episodes.seasonNumber])
      ..addColumns([episodes.number])
      ..addColumns([showId])
      ..groupBy([showId]);

    return historyQuery.watch().map((rows) {
      return rows.map((row) {
        return HistoryAdapter(
            row.read(showId),
            row.read(count),
            row.read(lastWatched),
            row.read(episodes.seasonNumber),
            row.read(episodes.number));
      }).toList();
    });
  }
```

I have two problems:

1. How do I get `MAX(history.watched_at)`?
2. The stream works when the table has 500 rows, but when it has 10000 rows the stream does not return any data. 
To test if something is wrong with the data, I imported the database on [sqliteonline.com](https://sqliteonline.com/) and performed the query above, but it worked fine.

**Comment by simolus3** [comment] 2020-10-29 20:46
> How do I get `MAX(history.watched_at)`?

If `watchedAt` is a number, you can just use `.max()` as you suspected. If it's a `DateTime`, you can use

```dart
    final lastWatched = history.watchedAt.secondsSinceEpoch.max();
```

> when it has 10000 rows the stream does not return any data

That's really weird. How are you listening to the stream? Can you please check if the stream emits an error (`snapshot.error` if you're using a `StreamBuilder`).

**Comment by Tiger3030** [comment] 2020-10-30 11:18
> If `watchedAt` is a number, you can just use `.max()` as you suspected. If it's a `DateTime`, you can use
> 
> ```dart
>     final lastWatched = history.watchedAt.secondsSinceEpoch.max();
> ```
Thanks, this works.

> That's really weird. How are you listening to the stream? Can you please check if the stream emits an error (`snapshot.error` if you're using a `StreamBuilder`).
Yes, I get an _SQLite Error 6410_.

I use to following packages:
```
moor: ^3.4.0
sqlite3_flutter_libs: ^0.2.0
path_provider: ^1.6.18
path: ^1.7.0
```

This solves my problem, but is it still the right solution, or is it deprecated?
```
@override
  MigrationStrategy get migration {
    return MigrationStrategy(beforeOpen: (details) async {
      await customStatement('PRAGMA temp_store = MEMORY;');
    });
  }
```

**Comment by simolus3** [comment] 2020-10-30 11:41
This sounds like a duplicate of #876 then, you can use `sqlite3.tempDirectory = (await getTemporaryDirectory()).path` to fix this.

**Closed** 2020-10-30 11:41 UTC
