### ISSUE TITLE
Accessing Joined table's column in OrderingTerm

### ISSUE THREAD

**Issue by AabhasS** [simolus3/moor#350] opened 2020-01-21 09:34 UTC
Hi,
I want to use OrderingTerm with expression equal to assets.area 
I can't find a way to do so currently 

![image](https://user-images.githubusercontent.com/24549095/72792598-4f680c00-3c5f-11ea-9179-4e0547dc49f4.png)

**Comment by simolus3** [comment] 2020-01-21 10:10
Duplicate of #347?

**Closed by simolus3** 2020-01-21 10:10 UTC
