### ISSUE TITLE
How we can uno all the last 3 4 query’s were execute on database to undo the values change in tables 

### ISSUE THREAD

**Issue by sadaqatdev** [simolus3/moor#2525] opened 2023-07-20 09:09 UTC
How we can uno all the last 3 4 query’s were execute on database to undo the values change in tables

**Comment by simolus3** [comment] 2023-07-20 09:44
Closing as duplicate of https://github.com/simolus3/drift/discussions/2524.

**Closed as completed by simolus3** 2023-07-20 09:44 UTC
