### ISSUE TITLE
 suddenly getting  59 lint notifications without preforming any changes to the database class

### ISSUE THREAD

**Issue by Hanibachi** [simolus3/moor#3232] opened 2024-09-21 16:56 UTC
exactly as described in the title.

![Screenshot from 2024-09-21 17-51-10](https://github.com/user-attachments/assets/2768d37a-0a5e-450f-b548-493e6fb73873)

**Comment by simolus3** [comment] 2024-09-21 20:54
I think this is a duplicate of https://github.com/simolus3/drift/discussions/3214, let's keep the discussion there.

Basically, I don't understand why this happens either because we have `ignore_for_file: lint` at the top of the generated code (can you check it's there to make sure?) that should ignore this error.

**Closed as not planned by simolus3** 2024-09-21 20:54 UTC
