### ISSUE TITLE
Can't update row twice in one function

### ISSUE THREAD

**Issue by 0rAX0** [simolus3/moor#214] opened 2019-10-29 09:59 UTC
Hey,

Context: This is related to #193 

I'm trying to get the results of two different queries to add to their corresponding row, but I'm seeing weird problems. The queries in question are producing the intended results. The first approach I took was this:

# Approach 1
```Dart

  updateTaskInfo() {
    final database = Provider.of<db.AppDatabase>(context);
    database
        .numberOfTasks(widget.project.id)
        .watchSingle()
        .distinct()
        .listen((value) {
      if (value != widget.project.projectTasksNumber) {
        database.updateProject(
          widget.project.copyWith(projectTasksNumber: value),
        );
      }
    });

    database
        .durationSum(widget.project.id)
        .watchSingle()
        .distinct()
        .listen((value) {
      if (value != widget.project.projectDuration) {
        database.updateProject(
          widget.project.copyWith(projectDuration: value),
        );
      }
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    updateTaskInfo();
  }

```

This, despite being a beginner solution works but only updates the database once, i.e. only the `ProjectDuration` gets updated, then after going into the element and back, the second info updates!

# Approach 2:

I thought I'd get them both into one function, extract the values to global variables and then create a 
```Dart
project = widget.project.copyWith(ProjectDuration: numberOfHours, projectTasks: numberOfTasks);
database.updateProject(project);
```

But it inserts 0 despite the fact that both `value`s, `numberOfHours`and `numberOfTasks` have the correct values in them!

--- 

I know that I'm probably struggling with this because I'm missing something obvious or doing it completely wrong, but I just wanted to report the behavior of the first approach just in case it's some kind of bug.

Thank you.

**Comment by simolus3** [comment] 2019-10-29 10:35
> I'm trying to get the results of two different queries to add to their corresponding row

I'm not entirely sure what you mean with this, can you expand a bit on what you're trying to achieve? Syncing state stored in the database with state stored in a widget?

In your first approach, you write
```dart
if (value != widget.project.projectTasksNumber) {
  database.updateProject(
    widget.project.copyWith(projectTasksNumber: value),
  );
}
```
Is the intention to copy the `projectTasksNumber` from the widget to the database? Here, the `value` parameter is the amount of tasks as stored in the database, correct? If you write `widget.project.copyWith(projectTasksNumber: value)`, the `projectTasksNumber` isn't actually updated in the database, because you're taking the old value you just received from the database. Or am I missing something here?

Another thing is that you're never cancelling the `StreamSubscriptions` created in `updateTaskInfo`. When `didChangeDependencies` is called, you might be listening to the same data twice.

In general, you can get a more detailed output on the sent queries by setting `logStatements` to `true` in the `FlutterQueryExecutor`. Maybe that can help to verify what data is sent to the database and when.

**Comment by 0rAX0** [comment] 2019-10-29 11:39
> I'm not entirely sure what you mean with this, can you expand a bit on what you're trying to achieve? Syncing state stored in the database with state stored in a widget?

Ah, sorry that was confusing. I have a database with projects in it, each project is expected to have a number of tasks and each task a duration. But upon creation of the project the task list and the duration is empty (0). 
<img width="286" alt="Screen Shot 2019-10-29 at 12 20 58 PM" src="https://user-images.githubusercontent.com/1044370/67762873-b0a88680-fa46-11e9-82a3-0a9f1d5a58d8.png">

Once the project is created, the user is expected to add their tasks inside and get a nice card on the main screen with the number of tasks and the total duration.

<img width="295" alt="Screen Shot 2019-10-29 at 12 21 41 PM" src="https://user-images.githubusercontent.com/1044370/67762905-c453ed00-fa46-11e9-9893-f206a982327b.png">

Now I opted to fetch/add the values to the database instead of querying them each and every time something reloads (But it's probably going to change since I'm querying them anyway), hence:

```Dart
if (value != widget.project.projectTasksNumber) {
  database.updateProject(
    widget.project.copyWith(projectTasksNumber: value),
  );
}
```
If the database already has the total counted and added, skip the update.

---

> Is the intention to copy the projectTasksNumber from the widget to the database? Here, the value parameter is the amount of tasks as stored in the database, correct? If you write widget.project.copyWith(projectTasksNumber: value), the projectTasksNumber isn't actually updated in the database, because you're taking the old value you just received from the database. Or am I missing something here?

No, I'm counting the number of tasks from a separate `Tasks` table and adding the `value` to the `Projects` table in a `ProjectNumberOfTasks` column. Then, if the new value from the query is the same as the one already in the database, skip the update.

I have enabled the log and it's even more confusing. Notice how it gets added, then becomes 0 then gets added again (I'm actually tapping into and out of the card). In another case, the update was more confusing than this, it updates with the CORRECT value say 5 from the existing 7, then, updates several times with 4, 5, 6, then goes to 7, while the duration remains correct. Then after a refresh it goes back to the correct value that got overridden.

```
flutter: Moor: Sent UPDATE projects SET project_name = ?, project_client = ?, project_rate = ?, project_color = ?, project_margin = ?, project_duration = ?, project_tasks_number = ? WHERE id = ?; with args [Project Gotham, Bruce Wayne, 454656, 0B0B84, 0, 0.0, 2, 11]
flutter: Moor: Sent UPDATE projects SET project_name = ?, project_client = ?, project_rate = ?, project_color = ?, project_margin = ?, project_duration = ?, project_tasks_number = ? WHERE id = ?; with args [Project Gotham, Bruce Wayne, 454656, 0B0B84, 0, 42.0, 0, 11]
flutter: Moor: Sent SELECT * FROM projects; with args []
flutter: Moor: Sent SELECT * FROM projects; with args []
flutter: Moor: Sent SELECT * FROM projects; with args []
flutter: Moor: Sent SELECT * FROM project_tasks WHERE project_id = ?; with args [11]
flutter: Moor: Sent UPDATE projects SET project_name = ?, project_client = ?, project_rate = ?, project_color = ?, project_margin = ?, project_duration = ?, project_tasks_number = ? WHERE id = ?; with args [Project Gotham, Bruce Wayne, 454656, 0B0B84, 0, 42.0, 2, 11]
```

**Comment by 0rAX0** [comment] 2019-10-29 12:21
<img width="782" alt="Screen Shot 2019-10-29 at 1 18 57 PM" src="https://user-images.githubusercontent.com/1044370/67766549-f5d0b680-fa4e-11e9-92fc-c218fdcb6128.png">

**Comment by simolus3** [comment] 2019-10-29 21:00
Thanks for the detailed explanation, I overlooked that the amount of tasks are coming from a different table.

Now, I could imagine that the problem with many updates (often with a wrong value) come from the fact that the stream subscriptions are never cancelled. The thing is, every time that `updateTaskInfo` is called, it adds two listeners to a database stream that will never go away. This isn't optimal because it leaks resources (the `State` will never be garbage collected, because the stream from the database has a reference to the State lambda passed to `.listen`). So what's probably happening is this:

1. the "Project details" screen is opened and the state subscribes to the two streams
2. The details screen is closed, but the state continues to listen and doesn't get garbage collected
3. The screen is re-opened and changes are made. The old state receives the update and writes its (wrong) value to the database. The new state writes the correct value to the database, but which one makes it is a race condition.

This should be rather easy to fix by something like
```dart
class StateWhichContainsTheUpdateMethod extends State<..., ...> {
  StreamSubscription _taskNumSub;
  StreamSubscription _taskDurationSub;

  updateTaskInfo() {
    _cancelOldSubscriptions();

    _taskNumSub = database.numberOfTasks(...).otherMethods().listen((value) {...});
    // same for taskDurationSub, assign it here
  }

  _cancelOldSubscriptions() {
    _taskNumSub?.cancel();
   _taskDurationSub?.cancel();
   _taskNumSub = null;
   _taskDurationSub = null;
  }
 
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    updateTaskInfo();
   }

  @override
  void dispose() {
    _cancelOldSubscriptions();
    super.dispose();
  }
 
  ...
}
```

**Comment by 0rAX0** [comment] 2019-10-30 10:18
Thanks for the guidance, @simolus3. I still have a very long way to go, apparently. :)

That solved the messages, but the behavior is still more or less the same. But thanks to you I understand what's happening and I will try to fix it somehow.

Once again, thank you and sorry for the false report. 👍

**Comment by simolus3** [comment] 2019-11-02 10:06
No problem. If you have any more questions or need guidance just let me know :) I'll close this issue in the meantime because it looks like moor is working as intended here.

**Closed by simolus3** 2019-11-02 10:06 UTC
