### ISSUE TITLE
Delete and autoincrement issue

### ISSUE THREAD

**Issue by sergiyvergun** [simolus3/moor#239] opened 2019-11-15 19:15 UTC
I was trying to implement AnimatedList with elements taken from Moor database, where element id was autoincrementing. So when I delete an element I have to delete it from AnimatedList and provide an element index in the list. I was sure that it has to be identical with id in the
 database, but it actually isn't.
After deletion instead of change ids of all elements in table, it just does nothing, so it causes unwanted consequences
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30001806/68969320-f609d980-07e4-11ea-8170-49cb14da8cab.gif)

**Comment by simolus3** [comment] 2019-11-15 21:17
>  After deletion instead of change ids of all elements in table, it just does nothing, so it causes unwanted consequences

In sqlite, the auto-increment doesn't reset after deleting rows, this is by design. So if you insert 5 rows, delete them, and then insert another one, the only row should have an id of 6. You can read more on autoincrement in [the sqlite documentation](https://www.sqlite.org/autoinc.html).

> I was sure that it has to be identical with id in the database, but it actually isn't.

The auto-increment id not counting down can be a bit counterintuitive, but as you've found out it's not suitable as an item index for a list. There are Flutter packages which can turn a `Stream<List<T>>` into an `AnimatedList` by automatically calculating the difference whenever the stream updates. A quick search on pub yields the `animated_stream_list` or the `implicitly_animated_list` packages which might achieve what you need.

I'm closing this as it looks like moor is working as intended, but if you have any questions please feel free to reply.

**Closed by simolus3** 2019-11-15 21:17 UTC

**Comment by gsouf** [comment] 2022-09-28 17:14
It is possible to reset the auto increment with the following custom query:

```dart
await database.customStatement("DELETE FROM SQLITE_SEQUENCE WHERE NAME='table_name'");
```

where `table_name` is the table for which we should reset the auto increment
