### ISSUE TITLE
How to give max length to column in moor from sql schema i.e tables.moor file.

### ISSUE THREAD

**Issue by ruthvik-github** [simolus3/moor#642] opened 2020-06-21 08:50 UTC
I have auto generated sql statements and it has max length shown below in tables.moor

```sql
CREATE TABLE "table" (
  "column1" INTEGER(2) NOT NULL,
  "column2"  TEXT(10) NOT NULL,
  "column3" INTEGER(19) NOT NULL DEFAULT 1,
  PRIMARY KEY ("column1")
);
```

In moor.dart file i have like this:
```dart
@UseMoor(
  include: {'tables.moor'})
class MoorDb extends _$MoorDb {
  MoorDb() : super(_openConnection());
```

After generating file and running it i got db.sqlite file with no max constraints.

How can i add size so the generated code can enforce it without creating class manually.

**Comment by simolus3** [comment] 2020-06-21 10:53
To my knowledge, length constraints in the type name don't have any effect. An `INTEGER(2)` is still a 64-bit int, and a `TEXT(10)` can store arbitrary lengths. I'm not sure if there's a pragma to enable those limits, but I think there isn't. If you want to enforce a maximum length, you'll have to use `"column2" TEXT NOT NULL CHECK(LENGTH("column2") <= 10)`

Moor rewrites the type name for a simpler implementation and to support features like `BOOLEAN` or `DATETIME` column types. Since that doesn't seem to affect anything, I'll close this for working as intended. If you can find a situation where the exact type name in the `CREATE TABLE` statement really matters, I'll gladly re-open this.

**Closed by simolus3** 2020-06-21 10:53 UTC
