### ISSUE TITLE
Moor is causing a bug in Dart compiler for 64-bit Android APKs

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#592] opened 2020-05-23 01:46 UTC
Issue: https://github.com/flutter/flutter/issues/57824

In my project, if I try to build a release APK, it only succeed for android-arm (android-arm64, android-x86 and android-x64 fails with `Exception: AOT snapshotter exited with code -1073740791`.

Just by commenting the return VmDatabase line, the build succeeds (so, I guessing moor_ffi has some kind of bug that is preventing an app to be built in release mode).

```dart
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getDatabasesPath();

    Directory(dbFolder).createSync(recursive: true);

    final file = File(path.join(dbFolder, "mcc.db"));

    //return VmDatabase(file, logStatements: true); <---- Uncoment for bug
  });
```

**Comment by simolus3** [comment] 2020-05-23 09:13
This is probably a duplicate of https://github.com/simolus3/moor/issues/581.

**Closed by simolus3** 2020-05-23 09:13 UTC
