### ISSUE TITLE
Generator issue  'users' could not be found in any import when .customConstraint('REFERENCES users(id)')

### ISSUE THREAD

**Issue by iampopal** [simolus3/moor#2598] opened 2023-09-06 20:34 UTC
**Describe the bug**

The new version of generator is having a big issue after updating our repo and drift version
The error is when write the following code: 
stock_orders.dart
```
  IntColumn get stockItemId => integer()
      .nullable()
      .customConstraint('REFERENCES stock_items(id) ON DELETE SET NULL')();
```
We get the following error when running: `dart run build_runner build --delete-conflicting-outputs`
we get the following warning and this warning not allow to completely generate other classes

```
[WARNING] drift_dev on lib/data/database/tables/fingers.dart:
line 12, column 25 of package:exact_server/data/database/tables/fingers.dart: `accounts` could not be found in any import.
   ╷
12 │       .customConstraint('REFERENCES accounts(id) ON DELETE SET NULL')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/stock_items.drift.dart:
line 20, column 25 of package:exact_server/data/database/tables/stock_items.drift.dart: `stock_units` could not be found in any import.
   ╷
20 │       .customConstraint('REFERENCES stock_units(id)')
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And at the next error is: 
````
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, StockUnits, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
```

**Comment by iampopal** [comment] 2023-09-06 20:36
stock_order.dart table: 
```
class StockOrders extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();

  IntColumn get stockItemId => integer()
      .nullable()
      .customConstraint('REFERENCES stock_items(id) ON DELETE SET NULL')();

  IntColumn get transferId => integer()
      .nullable()
      .customConstraint('REFERENCES transfers(id) ON DELETE CASCADE')();

  IntColumn get accountId => integer()
      .nullable()
      .customConstraint('REFERENCES accounts(id) ON DELETE SET NULL')();

  IntColumn get orderUnitId =>
      integer().customConstraint('REFERENCES stock_units(id)').nullable()();

  RealColumn get buy => real().nullable()();
  RealColumn get sell => real().nullable()();

  RealColumn get buyRate => real().nullable()();
  RealColumn get sellRate => real().nullable()();

  RealColumn get weight => real().nullable()();

  IntColumn get createdByUserId => integer().nullable()();
  DateTimeColumn get createdAt =>
      dateTime().withDefault(currentDateAndTime).nullable()();

  IntColumn get updatedByUserId => integer().nullable()();
  DateTimeColumn get updateAt => dateTime().nullable()();
}

```

stock_items.dart table
```

import 'package:exact_server/server.dart';

class StockItems extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();
  TextColumn get name => text().customConstraint('NOT NULL UNIQUE')();

  RealColumn get buyRate => real().nullable()();
  RealColumn get sellRate => real().nullable()();
  RealColumn get sellBuyRate => real().nullable()();

  IntColumn get buyCurrencyId =>
      integer().withDefault(Constant(1)).nullable()();
  IntColumn get sellCurrencyId =>
      integer().withDefault(Constant(1)).nullable()();

  TextColumn get details => text().nullable()();

  IntColumn get itemUnitId => integer()
      .customConstraint('REFERENCES stock_units(id)')
      .nullable()();

  IntColumn get createdByUserId => integer().nullable()();
  DateTimeColumn get createdAt =>
      dateTime().withDefault(currentDateAndTime).nullable()();

  IntColumn get updatedByUserId => integer().nullable()();
  DateTimeColumn get updateAt => dateTime().nullable()();

  RealColumn get weight => real().nullable()();
}

```

**Comment by iampopal** [comment] 2023-09-06 20:38
The complete error that not allow us build new version: 

```
[INFO] Generating build script completed, took 264ms
[INFO] Precompiling build script... completed, took 5.7s
[INFO] Building new asset graph completed, took 761ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 4ms
[WARNING] drift_dev on lib/data/database/tables/fingers.dart:
line 12, column 25 of package:exact_server/data/database/tables/fingers.dart: `accounts` could not be found in any import.
   ╷
12 │       .customConstraint('REFERENCES accounts(id) ON DELETE SET NULL')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/stock_items.drift.dart:
line 20, column 25 of package:exact_server/data/database/tables/stock_items.drift.dart: `stock_units` could not be found in any import.
   ╷
20 │       .customConstraint('REFERENCES stock_units(id)')
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transactions.dart:
line 24, column 25 of package:exact_server/data/database/tables/transactions.dart: `marks` could not be found in any import.
   ╷
24 │       .customConstraint('REFERENCES marks(id) ON DELETE SET NULL')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/accounts.dart:
line 17, column 7 of package:exact_server/data/database/tables/accounts.dart: `exact_files` could not be found in any import.
   ╷
17 │       'REFERENCES exact_files(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 11, column 7 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
11 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 14, column 7 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
14 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 17, column 7 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
17 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 23, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
23 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 27, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
27 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 31, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
31 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 35, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
35 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 39, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
39 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 43, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
43 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 47, column 11 of package:exact_server/data/database/tables/transfers.dart: `transactions` could not be found in any import.
   ╷
47 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/transfers.dart:
line 66, column 25 of package:exact_server/data/database/tables/transfers.dart: `fingers` could not be found in any import.
   ╷
66 │       .customConstraint('REFERENCES fingers(id) ON DELETE SET NULL')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/journal_transactions.dart:
line 7, column 7 of package:exact_server/data/database/tables/journal_transactions.dart: `transactions` could not be found in any import.
  ╷
7 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
[WARNING] drift_dev on lib/data/database/tables/journal_transactions.dart:
line 9, column 7 of package:exact_server/data/database/tables/journal_transactions.dart: `transactions` could not be found in any import.
  ╷
9 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
[WARNING] drift_dev on lib/data/database/tables/journal_transactions.dart:
line 12, column 7 of package:exact_server/data/database/tables/journal_transactions.dart: `transactions` could not be found in any import.
   ╷
12 │       'REFERENCES transactions(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/journal_transactions.dart:
line 15, column 11 of package:exact_server/data/database/tables/journal_transactions.dart: `transactions` could not be found in any import.
   ╷
15 │           'REFERENCES transactions(id) ON DELETE SET NULL')();
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/journal_transactions.dart:
line 18, column 7 of package:exact_server/data/database/tables/journal_transactions.dart: `transfers` could not be found in any import.
   ╷
18 │       'REFERENCES transfers(id) ON DELETE SET NULL')();
   │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/stock_orders.drift.dart:
line 8, column 25 of package:exact_server/data/database/tables/stock_orders.drift.dart: `stock_items` could not be found in any import.
  ╷
8 │       .customConstraint('REFERENCES stock_items(id) ON DELETE SET NULL')();
  │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
[WARNING] drift_dev on lib/data/database/tables/stock_orders.drift.dart:
line 12, column 25 of package:exact_server/data/database/tables/stock_orders.drift.dart: `transfers` could not be found in any import.
   ╷
12 │       .customConstraint('REFERENCES transfers(id) ON DELETE CASCADE')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/stock_orders.drift.dart:
line 16, column 25 of package:exact_server/data/database/tables/stock_orders.drift.dart: `accounts` could not be found in any import.
   ╷
16 │       .customConstraint('REFERENCES accounts(id) ON DELETE SET NULL')();
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/tables/stock_orders.drift.dart:
line 19, column 34 of package:exact_server/data/database/tables/stock_orders.drift.dart: `stock_units` could not be found in any import.
   ╷
19 │       integer().customConstraint('REFERENCES stock_units(id)').nullable()();
   │                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Accounts, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, AccountTypes, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Currencies, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, JournalTransactions, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, TransactionTypes, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Transactions, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Transfers, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Treasures, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, UserPermissions, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Users, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Marks, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Reminders, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, ReminderTypes, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, DatabasePreferences, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, ExactFiles, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Attachments, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, ExactFileTypes, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Fingers, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, StockItems, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, StockOrders, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, Activities, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/data/database/database_service.dart:
line 34, column 7 of package:exact_server/data/database/database_service.dart: The referenced element, StockUnits, is not understood by drift.
   ╷
34 │ class DatabaseService extends _$DatabaseService {
   │       ^^^^^^^^^^^^^^^
```

**Comment by iampopal** [comment] 2023-09-06 20:40
build.yaml file
```
targets:
  $default:
    builders:
      drift_dev:
        options:
          skip_verification_code: true
```

**Comment by iampopal** [comment] 2023-09-06 20:45
flutter doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.1 22C65 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by iampopal** [comment] 2023-09-06 21:00
my pubspec.yaml
---
```
name: exact
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  path: ^1.8.2
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  drift: ^2.11.1
  intl: ^0.17.0
  shelf_multipart: ^1.0.0
  shelf_virtual_directory: ^3.0.1
  file: ^6.1.4
  dart_jsonwebtoken: ^2.8.0
  supabase: ^1.9.8
  shelf_web_socket: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  drift_dev: ^2.11.1
```

**Comment by simolus3** [comment] 2023-09-06 21:58
The error on `REFERENCES` is probably because drift now validates the SQL you put there. Are the referenced tables imported into the Dart file using `REFERENCES`? Also note that we [now have built-in support for foreign keys](https://drift.simonbinder.eu/api/drift/buildcolumn/references).

The error about "... is not understood by drift" could be a bug when using `export` statements to import the table into the database or drift accessor. A temporary workaround until the next version would be to import the file defining the table directly. If you're not using exports, that's probably another bug I need to look at. But it would be good to know whether you're using `export`s like that to start the investigation.

**Comment by iampopal** [comment] 2023-09-07 05:25
Is it possible to disable all these errors and go as before or can your tell us about a version which not requires import and not check SQL we put in `.customConstraint`. 
We need a quick way to disable generator checking .customConstraint(SQL)

**Comment by iampopal** [comment] 2023-09-07 05:43
by importing all tables in `database_service.dart` which contains `part 'database_service.g.dart;'

The warning of ` `accounts` could not be found in any import.` still exists but the good thing is the generator worked and our new column are generated.

**Comment by simolus3** [comment] 2023-09-07 12:43
> can your tell us about a version which not requires import and not check SQL we put in

I think `drift_dev` version 2.3.3 was the last version to not do that.

> by importing all tables in `database_service.dart` which contains `part 'database_service.g.dart;'

You need to do this on a per-table basis. E.g `stock_order.dart` would have to import `stock_items.dart` for `REFERENCES stock_items(id)` to work (as well as the other references).

Did this fix the `is not understood by drift` issue though?

**Comment by iampopal** [comment] 2023-09-08 09:41
I have imported all tables to
database_service.dart
But the issue still not solve and drift is  still giving warning of
imports.

Will be great if we have an option to disable this import warnings or
drift_dev support exports

**Comment by simolus3** [comment] 2023-09-08 12:26
Could you try upgrading to `drift_dev: ^2.11.2` and report whether the exports are still necessary on that version?

**Comment by simolus3** [comment] 2023-09-12 15:06
Please let me know if the issue is still happening with the latest `drift_dev` version. Otherwise I consider this fixed since a very similar issue has been fixed in that version.

**Closed as completed by simolus3** 2023-09-12 15:06 UTC
