### ISSUE TITLE
Automigration

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#2309] opened 2023-02-09 15:44 UTC
**Is your feature request related to a problem? Please describe.**
In Room (androidx) there is a limited AutoMigration option, is it possible that this also will be available in drift ?

**Describe the solution you'd like**
Automigration option, on adding tables and adding new fields.

Just like AutoMigration in Room.

screenshot from one of my Room projects (in kotlin)

![image](https://user-images.githubusercontent.com/11217296/217860949-7ca50200-1a38-41db-a713-f55e4b10a7fd.png)

it is neat and easy

of course, more complex migration tasks need to be identified and specified.

**Comment by simolus3** [comment] 2023-02-10 16:18
Thanks for the suggestion! I think this is sort of a duplicate of https://github.com/simolus3/drift/issues/1390. It's a good reminder though, I should take a look at automating some common migration steps soon.

**Closed as completed by simolus3** 2023-02-10 16:18 UTC
Labels: enhancement
