### ISSUE TITLE
[Bug] Still showing error for double quotes in VS Code Plugin

### ISSUE THREAD

**Issue by North101** [simolus3/moor#323] opened 2020-01-06 14:01 UTC
<img width="573" alt="Screenshot 2020-01-06 at 14 00 47" src="https://user-images.githubusercontent.com/1031451/71822517-f3ad5880-308c-11ea-8642-0a2641147d13.png">
This only shows up after #322 shows its exception, so maybe it's an old error?

**Comment by simolus3** [comment] 2020-01-06 18:23
Yeah, the problem is that overridden dependencies don't apply to analysis server plugins, so it's still using the old, broken version.

If you need a solution quickly, you could checkout the moor repo locally and change [this file](https://github.com/simolus3/moor/blob/fd97a91798bde14db61e598d3c6d2a0fa4744a94/moor/tools/analyzer_plugin/pubspec.yaml#L11-15) so that the dependencies are properly overridden (you need to use absolute paths). In your main project, you could then change the git dependency to a path dependency. You might need to delete the `$HOME/.dartServer/.plugin_manager` directory as well, it acts like a cache for plugin code.

I can't really change the pubspec in this repo, since absolute paths are necessary. I'll close this issue since it likely isn't another bug.

**Closed by simolus3** 2020-01-06 18:23 UTC
