### ISSUE TITLE
LateError LateInitializationError: Field 'db' has not been initialized.

### ISSUE THREAD

**Issue by phijma** [simolus3/moor#1250] opened 2021-06-03 08:58 UTC
The reason I "file" a bug is that this was no problem before. :) If a user starts the app and is unauthenticated, I would like to log the user out and remove their database. But since using the new version of flutter + dart which has null safety and such, I get this error:

```
LateError: LateInitializationError: Field 'db' has not been initialized.
  File "encrypted_moor.dart", in _SqfliteDelegate.close
  File "engines.dart", line 310, in DelegatedDatabase.close
  File "db_base.dart", line 128, in GeneratedDatabase.close
  File "<asynchronous suspension>"
  File "app_db.dart", line 101, in AppDB.removeDatabase
  File "<asynchronous suspension>"
  File "authentication_service.dart", line 75, in AuthenticationService.removeUserData
  File "<asynchronous suspension>"
  File "base_screen.dart", line 42, in BaseScreen.build.<fn>
```

Any clue?

This is no problem of course when the user is authenticated and uses the logout button. As in the meantime the database is always initialized. This is only a problem if the user is authenticated, closes the app, and then restarts it.

**Comment by simolus3** [comment] 2021-06-03 10:02
Thanks for reporting this! Moor should handle closing a database that has never been opened. We have an integration test for this as well, and that does pass with `encrypted_moor`:

https://github.com/simolus3/moor/blob/ac30bb598946b0fbfb9e278e73cf9451c01e237c/extras/integration_tests/tests/lib/suite/suite.dart#L30-L34

Can you try to reproduce this with a simple example that I could take a look at? E.g., does it happen if you create a database (without using  it) and then call `close()` right away?

**Comment by phijma** [comment] 2021-06-03 10:21
I can! At the moment I don't have time. But I will in the upcoming days.

**Comment by simolus3** [comment] 2021-06-03 11:15
Yeah the `encrypted_moor` packages uses David's sqlcipher too.

**Comment by phijma** [comment] 2021-06-07 15:29
My first observation: this does not happen inside the simulator. So that could explain the tests succeed maybe. 

Simple example is very hard because of this observation.

**Comment by phijma** [comment] 2021-06-07 15:37
Observation: I can reproduce it in the Android simulator. Though it does lead to this error only **sometimes**.

That might explain that the tests do not fail in a way.

**Comment by davidmartos96** [comment] 2021-06-07 15:40
@phijma Can you try this?
```dart
final appDatabase = AppDatabase();
await appDatabase.close();
```
I'd say the problem is simply that there is no check for the app being open when closing it.

https://github.com/simolus3/moor/blob/ac30bb598946b0fbfb9e278e73cf9451c01e237c/extras/encryption/lib/encrypted_moor.dart#L77

**Comment by phijma** [comment] 2021-06-07 15:56
> @phijma Can you try this?
> 
> ```dart
> final appDatabase = AppDatabase();
> await appDatabase.close();
> ```
> 
> I'd say the problem is simply that there is no check for the database being open when closing it.
> 
> https://github.com/simolus3/moor/blob/ac30bb598946b0fbfb9e278e73cf9451c01e237c/extras/encryption/lib/encrypted_moor.dart#L77

Hm, that seems to work without a problem! So that is weird.

Maybe I'm doing something completely wrong in combination with riverpod.

**Comment by simolus3** [comment] 2021-06-07 16:02
We have that check in another wrapper:

https://github.com/simolus3/moor/blob/ac30bb598946b0fbfb9e278e73cf9451c01e237c/moor/lib/src/runtime/executor/helpers/engines.dart#L307-L316

There could technically be a scenario where `ensureOpen` has been called, but didn't complete. Then, `close()` is called and prematurely closes the underlying delegate.

**Comment by phijma** [comment] 2021-06-07 16:03
@simolus3 

> We have that check in another wrapper:
> 
> https://github.com/simolus3/moor/blob/ac30bb598946b0fbfb9e278e73cf9451c01e237c/moor/lib/src/runtime/executor/helpers/engines.dart#L307-L316
> 
> There could technically be a scenario where `ensureOpen` has been called, but didn't complete. Then, `close()` is called and prematurely closes the underlying delegate.

Would explain that it happens sometimes. (I've also updated my previous comment with a "wild guess")

**Comment by simolus3** [comment] 2021-06-07 16:41
Apart from the scenario I mentioned, there's another potential problem if `close()` is called multiple times.

Both problems should be fixed with the referenced commit.

**Closed by simolus3** 2021-06-07 16:41 UTC

**Comment by phijma** [comment] 2021-06-07 20:20
Thank you for the quick responses and even a fix @simolus3 

 I will try “the commit” tomorrow.

Let me use this moment to also thank you for flutter moor and @davidmartos96 as well for his package! Works very well.

**Comment by phijma** [comment] 2021-06-08 14:19
@simolus3 Tested and seems to work! No errors anymore on three different simulators.

Any idea when this might be released? Days, weeks or possibly months?

Thanks again.

**Comment by simolus3** [comment] 2021-06-08 14:56
A couple of weeks is a realistic timeframe I think. I'm a bit busy right now, and the next moor version contains a whole bunch of cool features that I still need to fledge out.

**Comment by flutterq2** [comment] 2021-06-22 07:10
All possible working solution added [[Solved] LateInitializationError: Field ‘_userData@78458596’ has not been initialized](https://fluttercorner.com/lateinitializationerror-field-userdata78458596-has-not-been-initialized/)

**Comment by peterhijma** [comment] 2021-06-24 11:27
> All possible working solution added [[Solved] LateInitializationError: Field ‘_userData@78458596’ has not been initialized](https://fluttercorner.com/lateinitializationerror-field-userdata78458596-has-not-been-initialized/)

How is this helping? I don't it does regarding this issue.

**Comment by North101** [comment] 2021-06-24 12:17
> > All possible working solution added [[Solved] LateInitializationError: Field ‘_userData@78458596’ has not been initialized](https://fluttercorner.com/lateinitializationerror-field-userdata78458596-has-not-been-initialized/)
> 
> How is this helping? I don't think it does regarding this issue.

based on the name and what they are linking to i think its just a spam account that copies stackoverflow (or similar), puts. some ads and then uses a bot to crawl through github and comment on posts linking to their site

**Comment by peterhijma** [comment] 2021-06-25 09:53
@simolus3 Sorry to bother you about this issue again. But do you consider it safe to temporarily fork the repo, add the fix of this issue to the master branch and use that?

Until a new version is out of course :)

**Comment by North101** [comment] 2021-06-25 09:55
> @simolus3 Sorry to bother you about this issue again. But do you consider it safe to temporarily fork the repo, add the fix of this issue to the master branch and use that?
> 
> Until a new version is out of course :)

You can use this to use the latest version (change beta to develop)
https://moor.simonbinder.eu/docs/internals/

**Comment by peterhijma** [comment] 2021-06-25 09:59
> > @simolus3 Sorry to bother you about this issue again. But do you consider it safe to temporarily fork the repo, add the fix of this issue to the master branch and use that?
> > Until a new version is out of course :)
> 
> You can use this to use the latest version (change beta to develop)
> https://moor.simonbinder.eu/docs/internals/

Yeah, but that is a lot more risky I guess? Instead of a stable version with only one change.

**Comment by simolus3** [comment] 2021-06-25 10:46
I've cherry-picked the fix onto the `fix-close-without-open` branch which is otherwise identical to `master` If you use git dependencies you only need to override `moor` since you'll be using the unchanged version from pub for the other packages.

**Comment by peterhijma** [comment] 2021-06-25 12:58
> I've cherry-picked the fix onto the `fix-close-without-open` branch which is otherwise identical to `master`. If you use git dependencies you only need to override `moor` since you'll be using the unchanged version from pub for the other packages.

Awesome! Thank you.

**Comment by peterhijma** [comment] 2021-07-05 08:45
@simolus3 I see it's included in 4.4.0 🥳 So for me: the branch could be closed again

**Comment by simolus3** [comment] 2021-07-05 09:48
Thanks for the reminder, I've deleted the branch :)
