### ISSUE TITLE
Any int inserting in db become very big, occur on android 6 and lower

### ISSUE THREAD

**Issue by godzeit** [simolus3/moor#640] opened 2020-06-19 19:22 UTC
Flutter: 1.17.3
moor: ^3.1.0 
moor_ffi: 0.5.0

For example, that id supposed to be 1, I am inserting id too by myself, but it getting inserted changed. Occurs on android 6 and lower and NOT occurs on EMULATOR. 

![photo_2020-06-19_21-03-57](https://user-images.githubusercontent.com/48680083/85173137-f6db8000-b28b-11ea-9947-d9f36d7f29df.jpg)

**Comment by simolus3** [comment] 2020-06-19 19:30
Are you building on Windows? This is probably a Dart compiler bug, see https://github.com/dart-lang/sdk/issues/42184. Moor can't do anything about this sadly, but it looks like using the `master` channel of Flutter will this fix problem. In a future Flutter update this will be fixed.

Closing as duplicate of https://github.com/simolus3/moor/issues/446.

**Closed by simolus3** 2020-06-19 19:30 UTC

**Comment by godzeit** [comment] 2020-06-19 19:36
Yes, I am building on Windows, will it work on MacOS on stable channel?

**Comment by godzeit** [comment] 2020-06-19 19:49
@simolus3 Yes, I am building on Windows, will it work on MacOS on stable channel?

**Comment by simolus3** [comment] 2020-06-19 19:58
Builds on macOS should work on all channels, yes.
