### ISSUE TITLE
Null pointer in moor_generator 

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#243] opened 2019-11-18 16:00 UTC
I have a DAO that sometimes fails generating when there is cached output from the build_runner, no matter if I add `--delete-conflicting-outputs` or not.

This does not always happen, sometimes it works fine and the cached output seems to be correct but when it occurs, then only a `flutter packages pub run build_runner clean` helps to resolve this.
Sometimes the first build after the clean fails and I have to retry several times until it works.

This very annoying on the CI system.

Version: 2.0.0/2.0.1

Output:
```
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 456ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 921ms

[INFO] Running build...
[INFO] Running build completed, took 89ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 167ms

[SEVERE] moor_generator:moor_generator on lib/db/foo/foo_dao.dart (cached):
Error running MoorGenerator
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
````

Verbose output:
```
[SEVERE] moor_generator:moor_generator on lib/db/foo/foo_dao.dart:
Error running MoorGenerator
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
dart:core                                                                       Iterable.toList
package:moor_generator/src/analyzer/runner/steps/analyze_dart.dart 48:60        AnalyzeDartStep.analyze
package:moor_generator/src/analyzer/runner/task.dart 183:45                     Task._analyze
package:moor_generator/src/analyzer/runner/task.dart 60:13                      Task.runTask
package:moor_generator/src/backends/build/moor_builder.dart 45:16               MoorBuilder.analyzeDartFile
package:moor_generator/src/backends/build/generators/moor_generator.dart 12:34  MoorGenerator.generate
package:source_gen/src/builder.dart 280:35                                      _generate
package:source_gen/src/builder.dart 73:15                                       _Builder._generateForLibrary
package:source_gen/src/builder.dart 67:11                                       _Builder.build
package:build                                                                   runBuilder
package:build_runner_core/src/generate/build_impl.dart 478:19                   _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15          _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 476:23                   _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                           NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 434:22                   _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                   Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 430:17                   _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 378:38                   _SingleBuild._runBuilder.<fn>
dart:async                                                                      Future.wait
package:build_runner_core/src/generate/build_impl.dart 377:36                   _SingleBuild._runBuilder
dart:async                                                                      _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 375:40                   _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 323:20                   _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                                      _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                          _SingleBuild._matchingPrimaryInputs
```

**Comment by simolus3** [comment] 2019-11-18 16:58
Thanks for the report. The line in question is 
```dart
accessor.resolvedQueries =
    availableQueries.followedBy(parser.foundQueries).toList();
```

I don't quite see how an NPE could even happen here - `parser.foundQueries` can't be null (its an initalized final field), and if `availableQueries` was null it shouldn't throw at `toList()`...

To help me reproduce this, can you try to describe what source changes trigger the error?  E.g. changes in the dao file itself, imports thereof, an imported moor file, ...

**Comment by kuhnroyal** [comment] 2019-11-18 17:36
There are no changes in this file since before the 2.0.0 update which we started using 2-3 weeks ago.
I think this started happening at some point after the update. It is not deterministic, most of the time it works.
In the beginning we didn't think much about it and just cleaned on the CI server but today I found the time to look at it a little closer.

**Comment by simolus3** [comment] 2019-11-18 19:06
A potential cause for this could be a moor file that somehow wasn't analyzed. Are you using moor files at all? Do you import one in the dao affected here?

**Comment by kuhnroyal** [comment] 2019-11-18 19:34
I added some debugging to the file in question to see what exactly is null there but it only logs in successful cases, not on errors. So somehow the message comes from cache.

There is one moor file imported in that particular DAO. Very simple:
```

CREATE TABLE Foo(
    id INTEGER NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);
```

**Comment by simolus3** [comment] 2019-11-20 11:07
Yeah, my best bet would be a moor file somehow not being analyzed so we'd expand something into a null-iterable, which should crash when `toList` is called in the end:
https://github.com/simolus3/moor/blob/598fef750ece8534ce54b43caff91e47780ff1a9/moor_generator/lib/src/analyzer/runner/steps/analyze_dart.dart#L37-L40

This might be the result of some ugly complication caused by rolling our own in-memory caching graph for analyzed files. I originally introduced that in moor 2.0 for faster builds and to support the analyzer plugin, but it doesn't look like it's speeding up builds a lot. The bulk work that happens in the build is analyzing Dart files, which the build system will cache either way.

I'll disable caching across build steps which should at least remove the non-determinism in builds. If the problem persists it should be easier to reproduce in the end.

**Comment by kuhnroyal** [comment] 2019-11-25 13:39
Ok, sounds good. Will let you know if it persists once this is released.

**Comment by simolus3** [comment] 2019-11-25 14:13
I've published version 2.1.1 of the generator yesterday, where I removed the custom cache. (That generator version can still support moor 2.0.0, if you can't upgrade because of an older Dart SDK on Flutter)

**Comment by kuhnroyal** [comment] 2019-11-26 16:26
So far the problem has not reappeared. 👍

**Comment by simolus3** [comment] 2019-11-26 20:07
Great! I'll close this issue but please let me know if it happens again. It should be easier to reproduce now if removing the cache didn't fix it.

**Closed** 2019-11-27 11:24 UTC
Labels: bug

**Comment by simolus3** [comment] 2019-11-28 20:35
I actually just hit the same exception during development. But it only happened after something else crashed before, causing an invalid state.
So if you encounter this again, try running the verbose build with `flutter packages pub run build_runner build -v` and check if there are any error messages before that.

**Comment by kuhnroyal** [comment] 2019-11-29 09:13
I was running with verbose and there was nothing.

**Comment by pkhivesara** [comment] 2020-04-06 14:20
@simolus3 I am running into the same error:

Stacktrace:

```pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:269:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

**Comment by simolus3** [comment] 2020-04-06 14:56
@pkhivesara There should be another error further up in the logs. It should contain `package:moor_generator` somewhere in its trace. Can you post that one as well?

**Comment by pkhivesara** [comment] 2020-04-06 15:29
@simolus3 Sorry! Updated log:

```
[SEVERE] moor_generator:moor_generator on lib/src/database/moor_database.dart (cached):
Error running MoorGenerator
NoSuchMethodError: The getter 'typeConverter' was called on null.
Receiver: null
Tried calling: typeConverter
dart:core                                                                       Object.noSuchMethod
package:moor_generator/src/model/table.dart 129:28                              MoorTable.converters.<fn>
dart:_internal                                                                  WhereIterator.moveNext
package:moor_generator/src/model/table.dart 133:29                              MoorTable._attachToConverters
package:moor_generator/src/model/table.dart 124:5                               new MoorTable
package:moor_generator/src/analyzer/dart/table_parser.dart 15:19                TableParser.parseTable
package:moor_generator/src/analyzer/dart/parser.dart 34:25                      MoorDartParser.parseTable
package:moor_generator/src/analyzer/runner/steps/parse_dart.dart 59:39          ParseDartStep._parseTable
package:moor_generator/src/analyzer/runner/steps/parse_dart.dart 33:15          ParseDartStep.parse
package:moor_generator/src/analyzer/runner/task.dart 126:35                     Task._parse
package:moor_generator/src/analyzer/runner/task.dart 41:26                      Task.runTask
package:moor_generator/src/backends/build/moor_builder.dart 28:18               MoorBuilder.analyzeDartFile
package:moor_generator/src/backends/build/generators/moor_generator.dart 24:34  MoorGenerator.generate
package:source_gen/src/builder.dart 298:35                                      _generate
package:source_gen/src/builder.dart 79:15                                       _Builder._generateForLibrary
package:source_gen/src/builder.dart 71:11                                       _Builder.build
package:build                                                                   runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19                   _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15          _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23                   _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                           NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22                   _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                   Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17                   _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38                   _SingleBuild._runBuilder.<fn>
dart:async                                                                      Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36                   _SingleBuild._runBuilder
dart:async                                                                      _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40                   _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20                   _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                                      _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                          _SingleBuild._matchingPrimaryInputs

[SEVERE] moor_generator:moor_generator on lib/src/database/moor_database.dart (cached):
Error running DaoGenerator
NoSuchMethodError: The getter 'typeConverter' was called on null.
Receiver: null
Tried calling: typeConverter
dart:core                                                                      Object.noSuchMethod
package:moor_generator/src/model/table.dart 129:28                             MoorTable.converters.<fn>
dart:_internal                                                                 WhereIterator.moveNext
package:moor_generator/src/model/table.dart 133:29                             MoorTable._attachToConverters
package:moor_generator/src/model/table.dart 124:5                              new MoorTable
package:moor_generator/src/analyzer/dart/table_parser.dart 15:19               TableParser.parseTable
package:moor_generator/src/analyzer/dart/parser.dart 34:25                     MoorDartParser.parseTable
package:moor_generator/src/analyzer/runner/steps/parse_dart.dart 59:39         ParseDartStep._parseTable
package:moor_generator/src/analyzer/runner/steps/parse_dart.dart 33:15         ParseDartStep.parse
package:moor_generator/src/analyzer/runner/task.dart 126:35                    Task._parse
package:moor_generator/src/analyzer/runner/task.dart 41:26                     Task.runTask
package:moor_generator/src/backends/build/moor_builder.dart 28:18              MoorBuilder.analyzeDartFile
package:moor_generator/src/backends/build/generators/dao_generator.dart 12:34  DaoGenerator.generate
package:source_gen/src/builder.dart 298:35                                     _generate
package:source_gen/src/builder.dart 79:15                                      _Builder._generateForLibrary
package:source_gen/src/builder.dart 71:11                                      _Builder.build
package:build                                                                  runBuilder
package:build_runner_core/src/generate/build_impl.dart 487:19                  _SingleBuild._runForInput.<fn>.<fn>.<fn>
package:build_runner_core/src/generate/performance_tracker.dart 300:15         _NoOpBuilderActionTracker.trackStage
package:build_runner_core/src/generate/build_impl.dart 485:23                  _SingleBuild._runForInput.<fn>.<fn>
package:timing/src/timing.dart 222:44                                          NoOpTimeTracker.track
package:build_runner_core/src/generate/build_impl.dart 442:22                  _SingleBuild._runForInput.<fn>
package:pool/pool.dart 127:28                                                  Pool.withResource
package:build_runner_core/src/generate/build_impl.dart 438:17                  _SingleBuild._runForInput
package:build_runner_core/src/generate/build_impl.dart 376:38                  _SingleBuild._runBuilder.<fn>
dart:async                                                                     Future.wait
package:build_runner_core/src/generate/build_impl.dart 375:36                  _SingleBuild._runBuilder
dart:async                                                                     _AsyncAwaitCompleter.start
package:build_runner_core/src/generate/build_impl.dart 373:40                  _SingleBuild._runBuilder
package:build_runner_core/src/generate/build_impl.dart 321:20                  _SingleBuild._runPhases.<fn>.<fn>
dart:async                                                                     _completeOnAsyncReturn
package:build_runner_core/src/generate/build_impl.dart                         _SingleBuild._matchingPrimaryInputs

[SEVERE] Build:
Failed after 131ms
pub finished with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:269:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


```

**Comment by simolus3** [comment] 2020-04-06 18:58
@pkhivesara That error message indicates that a column couldn't be parsed (#471). If you post the `lib/src/database/moor_database.dart` file (or privately send it to me at oss@simonbinder.eu) I can take a look at what's going wrong exactly, thanks!

**Comment by pkhivesara** [comment] 2020-04-06 23:20
@simolus3 I was able to figure it out. The issue was resolved once I removed the ``call()`` method.
Could you tell me how can I compare two ``Strings`` within a ``Where`` clause?
`` return  (select(dummyList)..where((t) => t.dummyListId.equals(parameterId))).watch();``

Here the ``dummyListId`` is ``GeneratedTextColumn`` and ``parameterId`` is ``String``. Is this correct?

**Comment by simolus3** [comment] 2020-04-07 14:13
That query looks correct to me. Can you enable `logStatements: true` on the `VmDatabase` or `FlutterQueryExecutor` and see if moor runs the statement you'd expect?

**Comment by pkhivesara** [comment] 2020-04-08 21:23
That worked as well. Sorry! One last question. Can I use a ``Transformer`` to manipulate the ``Stream``?

Does this seem correct?

``` return  (select(list)..where((t) => t.id.equals(id))).watch().transform(new StreamTransformer.
   fromHandlers(handleData: (value,sink){
     sink.add(value.insert(0, NewDummy()));
   }));```

**Comment by simolus3** [comment] 2020-04-09 07:32
Yeah - moor streams are regular streams that can be transformed. If you're seeing unexpected behavior when applying transformers please open another issue, thanks!
