### ISSUE TITLE
Batch insert returning row id

### ISSUE THREAD

**Issue by nissaba** [simolus3/moor#3389] opened 2024-12-21 15:32 UTC
I was trying to make a batch insert of related tables where one as a foreign key on the other, but the insert and insert are returning void; it would be beneficial to have a version of them that is returning the inserted row IDs so we can then follow the call with an insert that references the previously inserted row in a foreign key relation.  

Table A -> table b;
Table todos 
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    categoryId INT REFERENCES category(id)
END;

Table category
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT
END

My use case is that I am fetching entities from a rest client, and I need to insert a fair amount of them in my Flutter app, this causes a problem when watching the updates to the table as it will be a grouped table and I need to watch a section data VIEW I created out of the main tables.

**Comment by simolus3** [comment] 2024-12-22 11:27
Unfortunately this is not currently possible. Inside the `batch()` callback, you're just collecting statements to run for drift - they are not actually being run right away. That happens in a later step before the outer `batch` call completes.

So tracking dependencies between statements in batches to reference returned ids will not work in that setup. As an alternative, you could wrap the inserts in a `transaction` and enable `cachePreparedStatements` when creating the `NativeDatabase` - the effect will be similar to a batch (and drift will only emit a single update to watched queries for a transaction).

Closing as a kind-of duplicate of https://github.com/simolus3/drift/issues/3389.

**Closed as completed by simolus3** 2024-12-22 11:27 UTC
Labels: enhancement
