### ISSUE TITLE
[Enhancement] Use rx dart BehaviorSubject to watch a stream

### ISSUE THREAD

**Issue by KhatibFX** [simolus3/moor#72] opened 2019-07-10 09:29 UTC
I had a use case where I was listening to the same query stream from multiple pages. I understand that moor intelligently caches streams and returns the same previously created stream if the query was duplicate. However, the new subscriber can't read the last emitted value from the stream. rxdart BehaviorSubject can retain that last emitted value so new subscribers can access it.

**Comment by simolus3** [comment] 2019-07-10 11:15
Thanks for the issue. This is most likely a duplicate of #60, which has been fixed but not published yet. We're not using rxdart because of its size, but the streams have a behavior very similar to a `BehaviorSubject` as they will also emit the latest data to new subscribers.

**Closed by simolus3** 2019-07-10 11:15 UTC
