### ISSUE TITLE
Invalid plugin specification moor_ffi.

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#737] opened 2020-07-28 08:10 UTC
![image](https://user-images.githubusercontent.com/1920873/88637476-c7baf880-d0ec-11ea-8b8d-4fd501bcb999.png)
![image](https://user-images.githubusercontent.com/1920873/88637514-d6a1ab00-d0ec-11ea-91d4-288af7a84081.png)

Invalid plugin specification moor_ffi.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by simolus3** [comment] 2020-07-28 08:26
Duplicate of #727, see https://github.com/simolus3/moor/issues/727#issuecomment-662935493 for a workaround. I'll try to release a fix for this tomorrow.

**Closed by simolus3** 2020-07-28 08:26 UTC
