### ISSUE TITLE
generate each table in a single separate file 

### ISSUE THREAD

**Issue by salim-lachdhaf** [simolus3/moor#565] opened 2020-05-14 09:45 UTC
How is it possible to **_generate_** each table in a separate file, however i have a lots of tables and the `database.g.dart` gets messy and i want that each table will be generated in separate file to resolve the issue. I already solved `DAOs` separation but not for tables.

Note that i created my tables in separated classes but the generated code for table is in a single file. i tried also to add something like this:

```
part 'articles.g.dart';//<- i tried this 

class Articles extends Table {
  IntColumn get id => integer().autoIncrement()();
}
```
but there is no file articles.g.dart generated.

this is my database declration:

```
part 'mydatabase.g.dart';

@UseMoor(tables: [Articles], daos: [ArticlesDao])
class MyDataBase extends _$MyDataBase {
  MyDataBase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}
```

**Comment by fgblomqvist** [comment] 2020-05-14 12:38
There's an issue for this: #490 
Won't be happening anytime soon. That being said, you shouldn't really have to look in database.g.dart. Issue #114 will hopefully help to some degree since it at least prevents you from having to import database.g.dart at all times (if you only need the data class/model).

**Comment by simolus3** [comment] 2020-05-14 13:52
Yup, what @fgblomqvist said. I'll close this as duplicate of #490.

**Closed by simolus3** 2020-05-14 13:52 UTC
