### ISSUE TITLE
Warning database has been locked for 0:00:10.000000

### ISSUE THREAD

**Issue by sohedul** [simolus3/moor#164] opened 2019-09-28 02:47 UTC
Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction.
In my moor_database.g.dart file the DB has been locked for 10 second. The file generated code example: 
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
 ## Employee map(Map<String, dynamic> data, {String tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : null;
    return Employee.fromData(data, _db, prefix: effectivePrefix);
  }

**Comment by simolus3** [comment] 2019-09-28 07:14
Thanks for the report. I need more information to figure out what's going wrong though: Are you using transactions with your database? Do you override the `migrationStrategy`? Did you set any breakpoints that could cause queries to run slow?

**Comment by simolus3** [comment] 2019-12-24 13:11
I'll close this since I can't diagnose what's wrong here without having more information. If you can provide more details, or have something that can consistently be reproduced, please let me know. I'll then re-open this issue. Thanks!

**Closed by simolus3** 2019-12-24 13:11 UTC
Labels: needs-info
