### ISSUE TITLE
[Android web] wasm issue

### ISSUE THREAD

**Issue by AlxSidenko** [simolus3/moor#3096] opened 2024-07-17 15:28 UTC
I have the floating issue, when transactions not completing. This bug appears only on Android web (on other platforms everything works well). I am following the documentation and it seems i do all correct. What i need to check fo first?

**Comment by simolus3** [comment] 2024-07-17 21:30
I need more information about how you're setting up the database and what error you're getting (or does the transaction just hang forever?)

**Comment by AlxSidenko** [comment] 2024-07-18 07:52
@simolus3 the transaction is just hangs forever. 

I am using a prebuilt drift_worker.js file and sqlite3.wasm (drift version is 2.19.1 and files for this version)
<img width="326" alt="image" src="https://github.com/user-attachments/assets/04a5b379-7bf5-4f79-9e7b-3e0f3f6d1ec3">

Function that opens a database connection for web
```dart
import 'package:drift/drift.dart';

import 'package:drift/wasm.dart';

DatabaseConnection openDatabaseConnection(String name) {
  return DatabaseConnection.delayed(
    Future<DatabaseConnection>(() async {
      final WasmDatabaseResult result = await WasmDatabase.open(
        databaseName: name,
        sqlite3Uri: Uri.parse('sqlite3.wasm'),
        driftWorkerUri: Uri.parse('drift_worker.js'),
      );

      if (result.missingFeatures.isNotEmpty) {
        print('Using ${result.chosenImplementation} due to unsupported '
            'browser features: ${result.missingFeatures}');
      }

      return result.resolvedExecutor;
    }),
  );
}
``` 
The example of a query
```dart
@override
  Future<void> createOrUpdateBooking(Booking booking) async {
    await _database.transaction(() async {
      if (booking.contact != null) {
        await createOrUpdateContact(booking.contact!);
      }

      await _updateBookingTags(booking.tagIDs, booking.id);
      await _updateBookingTables(booking.tableIDs, booking.id);

      await _database.bookingsDao.createOrUpdateBooking(
        BookingMapper.toDatabase(booking, _restaurantId),
      );
    });
  }

Future<void> _updateBookingTags(
    List<String> tagIDs,
    String bookingId,
  ) async {
    await _database.transaction(() async {
      await _deleteTagsByBookingId(bookingId);
      await _addAllTagsToBooking(tagIDs, bookingId);
    });
  }
```

**Comment by AlxSidenko** [comment] 2024-07-18 08:19
@simolus3 and without transactions queries are not completed. My usage:
1. open web app
2. make 3-5 queries
3. after that queries are not completing
4. if I need queries to start working again, I restart Chrome

Drift worker is running
<img width="317" alt="image" src="https://github.com/user-attachments/assets/a2776242-fb6f-4b73-8ca7-b08679676664">

Database type
<img width="804" alt="image" src="https://github.com/user-attachments/assets/af27d624-cf7d-432c-b3be-4cc0aaa805a8">

**Comment by simolus3** [comment] 2024-07-18 12:38
This issue sounds related to something fixed with the `drift_worker.js` file from version 2.19.1. I'll take another look though.

To help me reproduce this, could you run your app once with this patched drift dependency?

```
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: wasm-logs
      path: drift
```

It will make `drift` emit logs for every request sent to the worker. Those logs might contain sensitive information, you can post them here or send them to me at oss@simonbinder.eu if you're more comfortable with that. Seeing the logs will hopefully make it much easier for me to find the exact sequence of steps necessary to reproduce this.

**Comment by AlxSidenko** [comment] 2024-07-18 13:46
@simolus3 sent logs to your email. 
This is small part when database is not working. After logs from chucker i am trying to sync data i database and after that nothing happened.
```
main.dart.js:58726 [IN]: SuccessResponse (id = 452): Instance of 'minified:U5'
main.dart.js:58726 [OUT]: Request (id = 465): StatementMethod.select: SELECT * FROM "booking_with_booking_tag_table" WHERE "booking_id" = ?; with [19]
main.dart.js:58726 ChuckerFlutter: Your notification setting is off. You can turn it on by visiting the settings page from Chucker Flutter screen.
main.dart.js:58726         
main.dart.js:58726 ChuckerFlutter: Your notification setting is off. You can turn it on by visiting the settings page from Chucker Flutter screen.
main.dart.js:58726         
main.dart.js:58726 [OUT]: Request (id = 466): RunTransactionAction(NestedExecutorControl.beginTransaction, null)
```

**Comment by bytepoets-jhe** [comment] 2024-07-23 09:05
I have a similar issues, try running with the debug version of sqlite.wasm
https://github.com/simolus3/sqlite3.dart/releases/tag/sqlite3_flutter_libs-0.5.22
Somehow I can't reproduce it with that. Is it the same for you?

**Comment by simolus3** [comment] 2024-07-25 11:37
Thanks a lot for the details @AlxSidenko! I think I have found the problem and fixed it in https://github.com/simolus3/sqlite3.dart/commit/a686c52fc4822970abbd640fe9c06bf6e230fb1e.

I can't reproduce the issue with that commit. Applying it requires a new drift worker but no code changes (https://storage.googleapis.com/simon-public-euw3/assets/drift/drift_worker.js). Could you check if you can still reproduce the problem with the updated worker?

**Comment by AlxSidenko** [comment] 2024-07-25 13:08
@simolus3 I've been using the app for 20 minutes now and it's working great. Thank you for your work and for your wonderful library.

**Closed as completed** 2024-07-25 13:14 UTC
Labels: backend-web-wasm
