### ISSUE TITLE
SQL Queries wrong type

### ISSUE THREAD

**Issue by fantastik78** [simolus3/moor#809] opened 2020-09-06 10:00 UTC
Hi,

I tried to use SQL queries in a DAO but in those queries I used a WHERE condition using DateTime parameter (BETWEEN start and end).

When running the build step, moor is generating both queries with parameters as double instead of DateTime. Maybe I'm doing something wrong.

The transactions table
```dart
@UseMoor(tables: [Transactions], daos: [TransactionDao])
class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  RealColumn get amount => real()();
  DateTimeColumn get date => dateTime()();
  BoolColumn get isEssential => boolean().nullable()();
  BoolColumn get isRecurrent => boolean().nullable()();
  IntColumn get categoryId => integer()();
}
```

The SQL queries
```dart
@UseDao(
  tables: [Transactions],
  queries: {
    'dayIncomes':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount >= 0 GROUP BY date(t.date);',
    'dayExpenses':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount <= 0 GROUP BY date(t.date);'
  },
)
```

The generated methods
```dart
mixin _$TransactionDaoMixin on DatabaseAccessor<FibDatabase> {
  Selectable<String> dayIncomes(double start, double end) {
    return customSelect(
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount >= 0 GROUP BY date(t.date);',
        variables: [Variable.withReal(start), Variable.withReal(end)],
        readsFrom: {}).map((QueryRow row) => row.readString('sum(t.amount)'));
  }

  Selectable<String> dayExpenses(double start, double end) {
    return customSelect(
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount <= 0 GROUP BY date(t.date);',
        variables: [Variable.withReal(start), Variable.withReal(end)],
        readsFrom: {}).map((QueryRow row) => row.readString('sum(t.amount)'));
  }
}
```

The issue is that I want to pass DateTime parameters and not double (double start, double end).

What I want to do is select all transactions between 2 dates, group them by day and get the sum of all their amount.
I tried with moor Dart API but without success, that why I wanted to achieve it using SQL.

Thank you for your time :)

**Comment by simolus3** [comment] 2020-09-06 11:23
Thanks for the report! However, I can't reproduce this locally. I setup a new Dart project depending on `moor` and `moor_generator` versions `^3.3.0`. I'm using the following content:

```dart
import 'package:moor/moor.dart';
part 'db.g.dart';

class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  RealColumn get amount => real()();
  DateTimeColumn get date => dateTime()();
  BoolColumn get isEssential => boolean().nullable()();
  BoolColumn get isRecurrent => boolean().nullable()();
  IntColumn get categoryId => integer()();
}
@UseMoor(
  tables: [Transactions],
  queries: {
    'dayIncomes':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount >= 0 GROUP BY date(t.date);',
    'dayExpenses':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount <= 0 GROUP BY date(t.date);'
  },
)
class Database extends _$Database {
  Database(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => throw UnimplementedError();
}
```

This generates a `dayExpenses(DateTime start, DateTime end)` and `dayIncomes` method, as I'd expect. Can you check that you're using the latest moor version too?

> I tried with moor Dart API but without success

This should work:

```dart
Selectable<double> dayIncomes() {
  final sum = transactions.amount.sum();

  final query = selectOnly(transactions)
    ..addColumns([sum])
    ..where(transactions.amount.isBiggerOrEqualValue(0))
    ..groupBy([transactions.date.date]);

  return query.map((row) => row.read(sum));
}
```

For now, you'll also need the following extension (but the function will be builtin in the next moor version):

```dart
extension on Expression<DateTime> {
  Expression<String> get date {
    return FunctionCallExpression(
      'DATE',
      [this, const Constant<String>('unixepoch')],
    );
  }
}
```

**Comment by fantastik78** [comment] 2020-09-06 15:00
@simolus3 I was not using the last version (3.1.0 instead of 3.3.0), I updated it but I run into the same issue.

By looking at you test, I saw that your queries were at the database level, with @UseMoor while on my side I was putting the queries in the @UseDao, at DAO level.

I switch my queries to the database level and it worked fine like that.
Can you check on your side that there is not an issue when using the queries at DAO level?

**Comment by simolus3** [comment] 2020-09-07 07:42
I'm now using

```dart
import 'package:moor/moor.dart';

part 'database.g.dart';

class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  RealColumn get amount => real()();
  DateTimeColumn get date => dateTime()();
  BoolColumn get isEssential => boolean().nullable()();
  BoolColumn get isRecurrent => boolean().nullable()();
  IntColumn get categoryId => integer()();
}

@UseMoor(
  tables: [Transactions],
  daos: [SomeDao],
)
class Database extends _$Database {
  Database(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => throw UnimplementedError();
}

@UseDao(
  tables: [Transactions],
  queries: {
    'dayIncomes':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount >= 0 GROUP BY date(t.date);',
    'dayExpenses':
        'SELECT sum(t.amount) FROM transactions t WHERE t.date BETWEEN :start and :end AND t.amount <= 0 GROUP BY date(t.date);'
  },
)
class SomeDao extends DatabaseAccessor<Database> with _$SomeDaoMixin {
  SomeDao(Database attachedDatabase) : super(attachedDatabase);
}
```

Still, no problems.

I saw that you had the `@UseMoor` annotation on a table class, but you need to use another class for your database. Also, make sure you're upgrading `moor_generator` too! Maybe `flutter pub run build_runner clean` helps as well.

**Comment by simolus3** [comment] 2020-09-10 08:52
Closing this since I can't reproduce this and it seems to work for me. If you still run into this problem (and have a good way to reproduce this), please let me know.

**Closed by simolus3** 2020-09-10 08:52 UTC
