### ISSUE TITLE
Comparison classes only generate in database class

### ISSUE THREAD

**Issue by CodeDoctorDE** [simolus3/moor#1218] opened 2021-05-25 05:56 UTC
**Is your feature request related to a problem? Please describe.**
I split my code in three parts. The first part is the frontend, the second the backend and a shared part.
In the shared part I have all my row classes and table definition. The database classes are in the separate front and backend package. The problem: I cannot access to the comparison class like UsersComparison to add this to the custom row class. These classes are in the package where the database is defined.

**Describe the solution you'd like**
The generator should generate the comparison classes in the same file (user.g.dart) like the table class.

**Comment by kuhnroyal** [comment] 2021-05-25 08:25
I think this is more or less a duplicate of https://github.com/simolus3/moor/issues/490

**Comment by simolus3** [comment] 2021-05-25 09:54
Yes, I'll close this as a duplicate.

**Closed by simolus3** 2021-05-25 09:54 UTC
Labels: enhancement
