### ISSUE TITLE
Result type unknown in SQL query using IIF

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#2400] opened 2023-04-26 14:22 UTC
**Describe the bug**
Based on the value of some column A, I want to return either the value or null for column B.

I tried to be more compact by using [SQLite's IIF](https://www.sqlite.org/lang_corefunc.html#iif), but when building Drift informs me that:
```
line 206, column 9: Expression has an unknown type, the generated code can be inaccurate.
```
I was already thinking about using a completely different method, but then I tried it using a `CASE` statement, and the build runner now ran successfully, and correctly inferred that the datatype of my resulting row should be `int?`.

(the original column B is already a nullable int, if that matters)

```sql
SELECT
  CASE
    WHEN a = 'foo' THEN b
    ELSE NULL
  END b_value -- The build runner realises b_value is of type 'int?'
FROM table;

SELECT
  IIF(a = 'foo', b, NULL) b_value -- The build runner doesn't know b_value's type
FROM table
```
It's no big deal for me right now, but I thought to report it anyways: I guess the evaluation of these statements may differ quite a bit under the hood, though I use them interchangably in my example.

And a final remark: Initially, I tried to help the `build_runner` by telling it that the resulting type should be an `int?`, but I couldn't get it to work or find any documentation on it. If it is in fact possible, it'd be nice to have some documentation on this. If not, then it's fine as it is I guess :)

**Comment by simolus3** [comment] 2023-04-27 09:34
You're right, type analysis support for `IIF` was missing. I've fixed it in this repository, but those changes haven't been released yet.
As a workaround in the meantime, you could add an explicit `CAST` around the `IIF` or use a `CASE WHEN` expression.

Closing this as a duplicate of https://github.com/simolus3/drift/issues/2392.

**Closed as completed by simolus3** 2023-04-27 09:34 UTC
