### ISSUE TITLE
[Isolates] ' symbols in the text lead to exceptions

### ISSUE THREAD

**Issue by zs-dima** [simolus3/moor#1179] opened 2021-05-05 20:56 UTC
' symbols in the text lead to exceptions in case of Isolates, however it works well for non-Isolates case (looks like serialization issue)

```sql
CREATE TABLE sample (
   title     TEXT,

@create: INSERT INTO sample (title) values  
('O''Connor'),
('Tomeo''s');
```

**Comment by simolus3** [comment] 2021-05-06 12:38
Thanks for the report, but I couldn't reproduce this unfortunately (see the referenced commit). Can you post more details on how this can be reproduced?

**Comment by zs-dima** [comment] 2021-05-06 13:15
@simolus3 - it could be reproduced for the moor Isolates use case
I provided example above when creating DB query lead to exception: `@create: INSERT INTO`

**Comment by zs-dima** [comment] 2021-05-06 13:17
@simolus3 queries generated by `@create:` moor file statement looks different then your test example.

**Comment by zs-dima** [comment] 2021-05-06 13:46
@simolus3 

Exception:
```
E/flutter (20466): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SqliteException(1): near "Connor": syntax error
E/flutter (20466): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:119:9)
E/flutter (20466): #1      _VmDelegate._runWithArgs (package:moor/src/ffi/vm_database.dart:193:11)
E/flutter (20466): #2      _VmDelegate.runCustom (package:moor/src/ffi/vm_database.dart:203:11)
E/flutter (20466): #3      _ExecutorWithQueryDelegate.runCustom.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:79:19)
E/flutter (20466): #4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:25:26)
E/flutter (20466): #5      _ExecutorWithQueryDelegate.runCustom (package:moor/src/runtime/executor/helpers/engines.dart:76:12)
E/flutter (20466): #6      ServerImplementation._runQuery (package:moor/src/runtime/remote/server_impl.dart:117:25)
E/flutter (20466): <asynchronous suspension>
E/flutter (20466): #7      MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter (20466): <asynchronous suspension>
```

**Comment by simolus3** [comment] 2021-05-06 13:55
Which moor and moor_generator version are you using? I tried adding this to a moor file:

```sql
CREATE TABLE sample (
   title     TEXT
);

@create: INSERT INTO sample (title) values  
('O''Connor'),
('Tomeo''s');
```

Then I added this test

```dart
  test('supports single quotes in text', () async {
    // Regression test for https://github.com/simolus3/moor/issues/1179
    final isolate = await MoorIsolate.spawn(_backgroundConnection);
    final custom = CustomTablesDb.connect(await isolate.connect());

    final result = await custom.customSelect('SELECT title FROM sample').get();
    expect(result.map((f) => f.read<String>('title')), ["O'Connor", "Tomeo's"]);
  });
```

That still works just fine for me.

**Comment by zs-dima** [comment] 2021-05-06 14:58
@simolus3 I using latest version:
moor_generator: ^4.2.2
moor: ^4.2.1
sqlite3_flutter_libs: ^0.4.1
path_provider: ^2.0.1
path: ^1.8.0
json_serializable: ^4.1.1
build_runner: ^2.0.2

**Comment by zs-dima** [comment] 2021-05-06 15:19
@simolus3 
It works fine without Isolates - so I guess it is not generator issue.
I reproduced it on Android emulator.

**Comment by zs-dima** [comment] 2021-05-07 08:36
@simolus3 
tested once more - exception still there on: `final result = await select(sample).get();`

**Comment by simolus3** [comment] 2021-05-08 19:01
Sorry, I still can't reproduce this. I created the moor file you posted in a new project and ran that on an isolate-powered database without issues. I've uploaded my attempt of a repro to https://storage.googleapis.com/simon-public-euw3/assets/repro_1179.tar.gz, does that not print the two names for you?

**Comment by zs-dima** [comment] 2021-05-08 22:05
@simolus3 thanks for example
`new_sql_code_generation: true` lead to this issue - here query generated with this parameter:
`'INSERT INTO sample (title) VALUES (\'O\'Connor\'), (\'Tomeo\'s\')')`
and here from your example without this parameter:
`'INSERT INTO sample (title) values  \n(\'O\'\'Connor\'),\n(\'Tomeo\'\'s\')')`

**Comment by simolus3** [comment] 2021-05-09 10:07
Ah, now I see it too. This problem is fixed on `development` already, which is why I didn't see it right away. Thanks for the report, this will be fixed in the next moor version.

**Closed by simolus3** 2021-05-09 10:07 UTC
