### ISSUE TITLE
Abort query if all stream listeners cancel while waiting for lock

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#1124] opened 2021-03-29 17:48 UTC
Consider the following example:

```dart
import 'package:moor/ffi.dart';
import 'package:moor/isolate.dart';
import 'package:moor/moor.dart';
import 'package:test/test.dart';

DatabaseConnection createConnection()
  => DatabaseConnection.fromExecutor(VmDatabase.memory(logStatements: true));

class EmptyDb extends GeneratedDatabase {
  EmptyDb.connect(DatabaseConnection c) : super.connect(c);
  @override final List<TableInfo> allTables = const [];
  @override final int schemaVersion = 1;
}

void main() {

  EmptyDb db;
  setUp(() async {
    final isolate = await MoorIsolate.spawn(createConnection);
    db = EmptyDb.connect(await isolate.connect());
  });

  int i = 0;
  String slowQuery() => '''
    with recursive slow(x) as (values(1) union all select x+1 from slow where x < 1000000)
    select ${i++} from slow;
  ''';     // ^ to get different `StreamKey`s

  test('abort on cancel', () async {
    final subscriptions = List.generate(4, (_) =>
      db.customSelect(slowQuery())
        .watch()
        .listen(null)
    );
    await pumpEventQueue();
    await Future.wait(subscriptions.map((e) => e.cancel()));

    await db.customSelect('select 1').getSingle();
  });

}
```

Here `select 1` waits for the previous slow queries to finish, even though those queries no longer have any listeners.

What we're seeing in practice is that without explicit effort to optimize anything, it's possible to slow down an app by repeatedly navigating to and from a query-heavy screen, since all the queries from previous screen-loads start to stack up.

Initially I thought this would be a matter of exposing sqlite's [interrupt](https://www.sqlite.org/c3ref/interrupt.html) api, but it's not that we want to interrupt whichever query sqlite is currently executing (nor would that be possible on all platforms moor targets) - we just want to avoid taking [this lock](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/executor/helpers/engines.dart#L14) if the caller no longer cares about the result. 

Async cancellation can get hairy pretty quickly, but perhaps it's manageable for the very specific case of:
- [`isSequential == true`](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/executor/helpers/engines.dart#L12)
- The query has not been sent to the database yet (i.e. it's waiting to take the lock)
- The query was created by a stream
- The stream no longer has any listeners

In the case where a subscriber re-listens to a query that's previously been cancelled, I'd imagine the listener would not receive any cancellation exceptions, and the query would be re-executed (basically just call `fetchAndEmitData` again?).

I hacked around for a bit, but it wasn't immediately clear to me how the `StreamQuery` apis should interact with the `QueryExecutor`'s lock. I imagine `QueryStreamFetcher.fetchData` would take some kind of object that can be checked for cancellations, and whoever constructs the `QueryStreamFetcher` would be responsible for wiring that into the `QueryExector`'s synchronization?

Curious if you have any thoughts!

**Comment by simolus3** [comment] 2021-03-29 18:40
Thanks for the detailed issue and your ideas!

I think we can make `DelegatedDatabase` return a `CancelableFuture` from `package:async` (well, if it's sequential). This isn't a breaking change since it extends `Future`. `cancel()` would only have an effect as long as we're waiting for the lock, but that's good enough to optimize your example.
The stream query implementation could then check if we have a `CancelableFuture` and cancel pending operations when a stream is closed.

The problem is that `CancelableFuture`s propagate poorly, as soon as we have one async/await or `.then` we're back to a regular future. The isolate protocol would need changes as well (we'd have to request cancellations with messages across isolates).

I'm not super happy with the current stream implementation (the `StreamQueryStore` shouldn't have to know what type a query stream returns!). I think we can avoid typed `QueryStreamFetcher`s and just make `fetchData` return a `List<Map<String, Object?>` representing all rows. This avoids further processing futures in higher-level apis, giving us a chance to return a cancelable future in `fetchData`. Higher-level apis should just call `.map` on what the low-level apis provide to map database responses.

**Comment by simolus3** [comment] 2021-03-29 20:37
Oh actually it looks like `CancelableFuture` is from the analyzer package and not from `package:async` :facepalm:  We could add something similar into moor but I think it's better to not make `Future` polymorphic.

That makes it much tougher to implement this without breaking changes. Maybe we can add a cancellation token as an optional parameter to the query methods as you suggested. Or we could add another set of `cancelableSelect`/... methods that return a `CancelableOperation` and default to returning an operation that isn't cancelable.

**Comment by simolus3** [comment] 2021-03-31 09:56
> I wonder if you could somehow leverage `Future.asStream`

I don't think we can make use of that without a custom future implementation, and even in that case `Stream.fromFuture` wouldn't work so it would be rather fragile.

> Or it might be handy to have an "interruption scope" api (similar to how transactions work) where you use zone values to pass around interrupt signals?

That's an interesting and non-intrusive api, I like it! Feels very `CoroutineScope`-ish :D I'll experiment with this a bit.

**Comment by simolus3** [comment] 2021-03-31 21:33
I started to play around with stream cancellations on the `stream-cancellations` branch. I added a test verifying that the expensive query is indeed not running more than once [here](https://github.com/simolus3/moor/blob/stream-cancellations/moor/test/integration_tests/cancellation_test.dart). It looks like other tests are failing now though, I'll take a look at that tomorrow.

Isolates were rather tricky since we need to relay the cancellation zone behavior over a communication channel (obviously zones don't work across isolates), but I think I've figured it out. In fact, this only really works on isolates since `moor/ffi` is synchronous so we can't really cancel queries asynchronously.

**Comment by Mike278** [comment] 2021-04-01 01:57
That looks brilliant! It's interesting to see how certain concurrency patterns look with Dart's eventloop + isolates setup compared to threads.

> In fact, this only really works on isolates

Hah yeah it took me a second to realize why the initial example wasn't working as expected before I added an isolate.

I'd love to give this a try - would it be possible to support this in `moor_flutter` as well? It has more or less the same semantics as isolates, and technically `FlutterQueryExecutor` is already sequential because sqflite performs its own locking, so I don't *think* setting `isSequential=true` would be a breaking change? Seems like it'd basically be just moving the waiters from sqflite's lock to moor's.

**Comment by simolus3** [comment] 2021-04-01 15:48
I've fixed a nullability issue in cc93fa8238f7f386312ed95e3c80fd12611f4a07 and made moor_flutter sequential in 12ab64a33ef4ea6e34b6efc8b7b286e093dcdfb5. Feel free to try it out, I'd love to see if that helps with performance on query-heavy screens.

**Comment by Mike278** [comment] 2021-04-02 17:25
Sweet, hoping to get a chance this weekend sometime :+1:

**Comment by Mike278** [comment] 2021-04-07 15:20
Finally got a chance to try this out. In our case we actually fixed the original problem by tweaking some queries and adding some indexes (which I had to actually revert in order to properly try this), but this is definitely still generally helpful. For example if you have something like `someUIFilter.switchMap(someSlowQuery)`, users are likely to rapidly change `someUIFilter` to get their results faster, which actually makes the app even slower without stream cancellation. It can be tricky to optimize all cases when you have lots of dynamically built queries, so its always possible for users to construct a slow query with the right combo of filters and/or data.

I tried a few other scenarios that were hard to examine just by using the app, but I encountered some unexpected test failures. For example if I replace `await db.doWhenOpened((e) {});` with `await db.customSelect('select 1').getSingle();`, the test occasionally fails with `Expected: (<0> or <1>) Actual: <2>`.

**Comment by simolus3** [comment] 2021-04-15 18:58
Thanks for the updated tests! I think that this is essentially a race condition (that isn't harmful in a real app, it just affects cancellations). If the background isolate started to process the query when a cancellation comes in, it's too late obviously. I don't fully understand why the initial select makes matters worse here, but it shouldn't matter too much.

Still, I've fixed a wrongly placed cancellation check in the background isolate and added your test (with the initial select) too.

**Comment by simolus3** [comment] 2021-04-19 19:40
I've now merged this to develop, so it will be part of the next moor release.

**Closed by simolus3** 2021-04-19 19:40 UTC
Labels: enhancement

**Comment by Mike278** [comment] 2021-05-23 19:26
Awesome, thanks so much as always!
