### ISSUE TITLE
Generation Errors When Using 'Address' As Table Name

### ISSUE THREAD

**Issue by KuroodoD** [simolus3/moor#3137] opened 2024-08-09 22:26 UTC
**Describe the bug**

If "Address" is used as a table name, the resulting database.g.dart file after running `dart run build_runner build` results in various errors.

Try adding a table defined as in the **database.dart** file which sets up the database. Additional columns are irrelevant.
```
class Address extends Table {
  IntColumn get id => integer().autoIncrement()();
}
```
Now run `dart run build_runner build` to generate the database.g.dart file. You should see various errors.
![image](https://github.com/user-attachments/assets/9b638749-4f79-450e-adba-1cc2cf05f64f)

If the Address table is defined in a separate file, regardless of file name, these errors are presented instead
![image](https://github.com/user-attachments/assets/f5baafaf-07fc-40f8-a687-745b425ad64a)

Sample project including the broken database.g.dart file:
[drift_bug.zip](https://github.com/user-attachments/files/16567371/drift_bug.zip)

Drift 2.19.1+1
Flutter 3.22.3
Windows 10

**Comment by simolus3** [comment] 2024-08-10 20:02
Thanks for the detailed report! This is a duplicate of https://github.com/simolus3/drift/issues/3117, which has been fixed in https://github.com/simolus3/drift/commit/29a30eb80796100ef73a1c15b2cea9d2ea361745, so this will be fixed in the next drift version.

As a workaround until then, you can add a `@DataClassName` annotation to the affected table:

```dart
@DataClassName('AddressData')
class Address extends Table {
  IntColumn get id => integer().autoIncrement()();
}
```

**Closed as completed by simolus3** 2024-08-10 20:02 UTC
