### ISSUE TITLE
Insert and update on Android 9 moor_ffi

### ISSUE THREAD

**Issue by bzee-art256** [simolus3/moor#477] opened 2020-04-06 16:22 UTC
Having issues with inserting and updating records when using Android 9.
using moor 2.4.2, moor_ffi 0.4.0
VS Code as IDE

- Debug app no issues with Android 7,8,9
- Release app issues with Android 9
- Release app created db just will not insert or update
 
- Debug app on 9 and then install release and it will read inserted data by debug version but still no update or insert
 
- Gave permission for read write storage no effect (don't think sqlite needs them)

Searched for issues with Android 9 and sqlite and found db.disableWriteAheadLogging() but don't know how to set in moor

Tried same app using moor_flutter without any issues on Android 7,8,9

Thanks, moor is a great lib for flutter db apps

**Comment by simolus3** [comment] 2020-04-06 19:00
Thanks for the detailed report! This might be an issue with `dart:ffi` that I'm still investigating.

Can you reproduce this on all devices on Android 9 or only on some models? We were seeing some issues with 32-bit arm devices, but regardless of their version.

**Comment by bzee-art256** [comment] 2020-04-06 21:03
I originally noticed it when testing a release build on a Samsung SM-T510 tablet, which you are correct it is a android-arm 32.

I have been using a rooted Moto G-4 to test most apps. Originally it was Android 8 arm64 and moor_ffi worked without issues. I flashed Android 9 to test if it was a Android 9 issue and you are correct the rom I flashed is a 32bit. 

I will do more tests:
- flash 9 64bit and test
- flash 8 32bit and test

Thanks for fast reply

**Comment by bzee-art256** [comment] 2020-04-07 12:09
Update of tested.

- Android 8 32 - works
- Android 8 64 - works
 
Looks like 9 32bit is the only one that has failed for me.

Will let you know when I install 9 64.

**Comment by simolus3** [comment] 2020-06-21 10:58
This is likely because of a Dart compiler bug that has been fixed in the meantime (see https://github.com/flutter/flutter/issues/54948). Switching away from the stable Flutter channel (beta will work) should fix this. This only happens when building on Windows, so if you want to keep using the stable channel you could consider building release versions of your app on macOS or Linux.

**Closed by simolus3** 2020-06-21 10:58 UTC
