### ISSUE TITLE
equalsExp missing

### ISSUE THREAD

**Issue by ltOgt** [simolus3/moor#277] opened 2019-12-12 20:01 UTC
I was reading the [documentation](https://moor.simonbinder.eu/docs/advanced-features/joins/) about performing joins, which states that one should use `equalsExp` for the column matching:

```
Stream<List<EntryWithCategory>> entriesWithCategory() {
  final query = select(todos).join([
    leftOuterJoin(categories, categories.id.equalsExp(todos.category)),
  ]);

```
This gives me the following error:
 `The method 'equalsExp' isn't defined for the class 'GeneratedIntColumn'.` 

I reverted back to moor version 1.6.0 and found that the `GeneratedIntColumn` was defined in `columns.dart` as:
`class GeneratedIntColumn extends GeneratedColumn<int, IntType>
    with ComparableExpr
    implements IntColumn`

the Mixin `ComparableExpr` is missing in the newer versions:
`class GeneratedIntColumn extends GeneratedColumn<int, IntType>
    implements IntColumn`

Is this by design?
If so what is the new way of performing joins with moor?
It would be nice if the documentation would reflect this change as well.

Thank you for your work on this awesome package!

**Comment by simolus3** [comment] 2019-12-12 20:13
`equalsExp` is still the right method - although it has moved to the more general `Expression` class (from which `GeneratedIntColumn` inherits).

> the Mixin `ComparableExpr` is missing in the newer versions [...] Is this by design?

It is, but that shouldn't break any code using moor. Some comparison operators have been re-introduced as extensions, others were moved to the `Expression` class. The public api didn't change here.

I'm a bit surprised about the error you're seeing - we're using `equalsExp` in a way that's very similar to your example, and it still works:
https://github.com/simolus3/moor/blob/e983e4da63c3a4655511130db4a3de3ac489fb78/moor/test/join_test.dart#L19-L21

**Comment by ltOgt** [comment] 2019-12-12 20:30
Thank you for the quick response.

I cleared the .pub-cache a few times and now everything seems to be working fine.

I can reproduce the problem if I manually specify `moor: ^2.1.0` in my `pubspec.yaml`.
If I do not specify the moor dependency directly and only use moor_flutter, everything works fine.

**Comment by simolus3** [comment] 2019-12-12 20:47
In that case it would be interesting to see the difference in the `.packages` file (the lines starting with moor) between the direct dependency and the transitive via moor_flutter.

**Comment by ltOgt** [comment] 2019-12-12 21:16
Now I get 
```
moor:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.1.1/lib/
moor_flutter:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor_flutter-2.0.0/lib/
moor_generator:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-2.0.0/lib/
```

for both direct `moor: ^...` and transitive.
The Error now shows up again in both cases.

Only if i specify `moor: 2.0.0` do I get
```
moor:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.0/lib/
moor_flutter:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor_flutter-2.0.0/lib/
moor_generator:file:///opt/AppDev/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-2.0.0/lib/
```
which again solves the issue.

I think I might have done this before as well, and the `pubspec.lock` forced version 2.0.0 after I removed the direct import:

```
  moor:
    dependency: transitive
    description:
      name: moor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
```
The only version in my .pub-cache now is 2.0.0, for transitive and cleaned cache before `flutter packages get`

**Comment by simolus3** [comment] 2019-12-12 21:43
So it seems like it's a moor 2.1.0 thing. I'll do an exact diff tomorrow and try tracking this down. 
Can you tell me your Dart/Flutter version? Since the method [does exist](https://pub.dev/documentation/moor/latest/moor_web/Expression/equalsExp.html), this might be some issue with the analyzer.

**Comment by ltOgt** [comment] 2019-12-12 21:56
```
$ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

**Comment by simolus3** [comment] 2019-12-13 10:19
I just tried to reproduce this on the same flutter version with a new project, but it worked for me.

Some ideas to help troubleshooting:
- you're only importing `package:moor_flutter/moor_flutter.dart`, correct? So no implementation imports anywhere
- You could check whether this is a general problem or just something with the analyzer. If you use `equalsExp` somewhere and get the error, can you still run the project with `flutter run`? If you can, it's definitely the analyzer acting up. Otherwise the some files in the pub cache might be unreadable, but it's weird since you already cleared the cache

**Comment by ltOgt** [comment] 2019-12-13 14:48
I am only ever importing `moor_flutter.dart`, yes.

I found that my analyzer and plugin got reverted to earlier versions somehow.
I cleaned those packages out of the cache and lock and they are now back to the newest version.
The problem seems to persist though.

I have currently some errors in my project, but I will try running after I have cleaned up some things and will report back.

**Comment by simolus3** [comment] 2020-01-19 19:51
Hi @ltOgt, are you still running into this issue?

I checked a couple of moor versions by downloading the tar directly from pub, they all contain the `equalsExp` method. It doesn't seem like a problem with moor directly, so I'll close the issue. If you still have this problem, please let me know.

**Closed by simolus3** 2020-01-19 19:51 UTC
