### ISSUE TITLE
add bool column error when migrator

### ISSUE THREAD

**Issue by lzhAndroid** [simolus3/moor#1650] opened 2022-01-24 08:59 UTC
I/flutter (24710): │ SqliteException(1): SQL logic error
I/flutter (24710): │   Causing statement: ALTER TABLE word_info ADD COLUMN is_delete INTEGER NOT NULL DEFAULT 0 CHECK (is_delete IN (0, 1));
I/flutter (24710): │ #0   DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:129:9)
I/flutter (24710): │ #1   _VmDelegate._runWithArgs (package:drift/src/ffi/database.dart:203:11)
I/flutter (24710): │ #2   _VmDelegate.runCustom (package:drift/src/ffi/database.dart:213:11)
I/flutter (24710): │ #3   _BaseExecutor.runCustom.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:109:19)
I/flutter (24710): │ #4   _BaseExecutor._synchronized (package:drift/src/runtime/executor/helpers/engines.dart:55:20)
I/flutter (24710): │ #5   _BaseExecutor.runCustom (package:drift/src/runtime/executor/helpers/engines.dart:105:12)
I/flutter (24710): │ #6   DatabaseConnectionUser.customStatement.<anonymous closure> (package:drift/src/runtime/api/connection_user.dart:382:23)
I/flutter (24710): │ #7   DatabaseConnectionUser.doWhenOpened.<anonymous closure> (package:drift/src/runtime/api/connection_user.dart:154:64)

**Comment by lzhAndroid** [comment] 2022-01-24 09:00
BoolColumn get isDelete => boolean().withDefault(Constant(false))();

**Comment by lzhAndroid** [comment] 2022-01-24 09:02
run ALTER TABLE word_info ADD COLUMN is_delete INTEGER NOT NULL DEFAULT 0 CHECK (is_delete IN (0, 1)) at database,it's ok.but sqlite3_exec return error message.error code is 1

**Comment by lzhAndroid** [comment] 2022-01-24 09:03
drift: ^1.1.0

**Comment by simolus3** [comment] 2022-01-24 12:36
Thanks for the report. Not easy to find, but this is a duplicate of https://github.com/simolus3/moor/issues/1633 and actually turned out to be a sqlite3 bug.

This only affects boolean columns being added to an existing table. This will be fixed in the next sqlite3 version, until then my recommendation is to run the alteration manually and to omit the `CHECK` which mainly serves as an additional safeguard: `customStatement('ALTER TABLE word_info ADD COLUMN is_delete INTEGER NOT NULL DEFAULT 0;')`

**Closed by simolus3** 2022-01-24 12:36 UTC

**Comment by lzhAndroid** [comment] 2022-01-25 02:23
Is there an option to ignore this check?
