### ISSUE TITLE
Custom query generated type missing nullables

### ISSUE THREAD

**Issue by galacticgibbon** [simolus3/moor#3047] opened 2024-06-12 07:20 UTC
**Describe the bug**

I have a query like so:

```
  queries: {
    'statsQuery': '''
      WITH periods AS (
        SELECT
          CASE 
            WHEN :period = 'weekly' THEN strftime('%Y-%W', date(date, 'weekday ' || :startOfWeek))
            ELSE date
          END as period,
          amount
        FROM entry_rows
        WHERE task_id = :taskId
        AND deleted = 0
        AND date >= :start
        AND date < :end
      ),
      aggregated_periods AS (
          SELECT
              period,
              SUM(amount) AS amount
          FROM 
              periods
          GROUP BY 
              period
      ),
      best_period AS (
          SELECT
              *
          FROM 
              aggregated_periods
          ORDER BY 
              amount DESC
          LIMIT 1
      )
      SELECT
        (SELECT period FROM best_period) as best_period,
        (SELECT amount FROM best_period) as best_amount,
        (SELECT SUM(amount) FROM aggregated_periods) as total_amount,
        (SELECT AVG(amount) FROM aggregated_periods) as average_amount
  ''',
  },
```

This generates a type where
best_period is `String` (not sure why this is not nullable when best_amount isn't since they come from the same query)
best_amount is `int?` 
total_amount is `int?`
average_amount is `double`

However, sometimes the query can return no rows, so the return type needs to be nullable for each property, and when there are no rows I get a type error before I can even read the row.

I've been able to trick the type system into giving me nullable types like so as a workaround.

```
        (SELECT case when period is null then null else period end FROM best_period) as best_period,
        (SELECT amount FROM best_period) as best_amount,
        (SELECT SUM(amount) FROM aggregated_periods) as total_amount,
        (SELECT case when AVG(amount) is null then null else AVG(amount) end FROM aggregated_periods) as average_amount
```

I wasn't sure if I was misusing drift or if there's a bug! So I thought I'd write an issue.

**Comment by simolus3** [comment] 2024-06-12 20:46
Thanks for the report! Yeah, this looks like a bug and we should make subquery expressions nullable.

**Comment by simolus3** [comment] 2024-06-12 21:03
This will (well, should) be fixed in the next release. If you give me the definition of `entry_rows` I can check that it works with your query, it might be something else when the type inference has to jump through many steps (like here with the CTEs).

**Comment by galacticgibbon** [comment] 2024-06-13 06:02
Great 👍🏼 

```
class EntryRows  {
  TextColumn get taskId => text()();
  TextColumn get date => text()();
  IntColumn get amount => integer()();
  BoolColumn get skip => boolean()();
}
```

Let me know if you need anything else

**Comment by simolus3** [comment] 2024-06-15 20:15
Well the table is missing an `extends Table` and a `deleted` column referenced in the query, but I can confirm that the fields are nullable as they should be with that fix.

**Closed as completed by simolus3** 2024-06-15 20:15 UTC
Labels: bug, package-sqlparser, area-analyzer
