### ISSUE TITLE
barrel files break modular generation

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2589] opened 2023-09-03 01:11 UTC
**Describe the bug**

In my app I am using barrel files to bundle my exports.
When using those barrel files to access my modularly generated `Tables`, drift fails to correctly associate them.

When running `build_runner`, I get the following warning:
`The referenced element, MyTable, is not understood by drift.`
And a broken generated file, where MyTable is not a getter.

I have setup a reproducible sample for this issue.
The following files are required:

**my_table.dart**
```dart
import 'package:drift/drift.dart';

// ignore: unused_import
import 'my_table.drift.dart';

class MyTable extends Table {
  IntColumn get id => integer().autoIncrement()();
}
```

**barrel.dart**
```dart
export 'my_table.dart';
```

**database.dart**
```dart
/// demonstrate a weird issue with drift and barrel files
///
/// this is valid:
/// import 'my_table.dart';
///
/// this is not valid:
/// import 'barrel.dart';
///
/// instead we get:
/// [WARNING] drift_dev:analyzer on lib/database.dart:
/// line 27, column 7 of package:barrel_example/database.dart: The referenced element, MyTable, is not understood by drift.
///    ╷
/// 27 │ class AppDatabase extends $AppDatabase {
///    │       ^^^^^^^^^^^
///    ╵
library;

import 'package:drift/drift.dart';
import 'database.drift.dart';

import 'barrel.dart';

// uncommenting this "fixes" the issue
// import 'my_table.dart';

@DriftDatabase(tables: [MyTable])
class AppDatabase extends $AppDatabase {
  AppDatabase(super.e);

  @override
  int get schemaVersion => 1;
}
```

using package imports over relative imports made no difference in my testing.

**Comment by simolus3** [comment] 2023-09-03 20:38
Thanks for the report!

This bug has probably been introduced by a recent optimization: We serialize which file defines which tables during the build. When analyzing files later, we can then quickly check whether a given class is a valid drift table without having to analyze the file again. This is more relevant for imports in SQL, where we don't know the table class beforehand and would potentially have to analyze every import. This optimization requires us to serialize Dart's import model as well though, and this hasn't considered export elements yet. This has been fixed in 79dda8668b8b4280dcb346cc87e2c8d3dacc260a.

**Closed as completed by simolus3** 2023-09-03 20:38 UTC

**Comment by camillobucciarelli** [comment] 2023-09-07 15:02
When a new hotfix release is planned?

**Comment by simolus3** [comment] 2023-09-07 15:25
I've just published `drift_dev` version 2.11.2 which contains the fix.

**Comment by camillobucciarelli** [comment] 2023-09-07 17:03
I continue to have problems.
I have a multipackage repo, something like the following struct:

    app
    |_features
        |_featureA
        |_featureB
        |_db

every feature exports its own tables and daos are properly configured. All has worked fine since version 2.11.1, now:

- In the _db_ package I have the following error: 
```
The referenced element, FeatureADataSourceImpl, is not understood by drift
```
- but in the fetureA I have:
```
@LazySingleton(as: FeatureADataSource)
@DriftAccessor(tables: [FeatureA])
class FeatureADataSourceImpl extends DatabaseAccessor<AppDatabase> with _$FeatureADataSourceImplMixin implements FeatureADataSource {
  FeatureADataSourceImpl(super.attachedDatabase);
  ...
}
```
and the export in the feature_a.dart file.

How i can solve?

**Comment by simolus3** [comment] 2023-09-07 20:26
Does `featureA` depend on `drift_dev` as well? That's necessary now for drift to see its members now since the analysis happens on a per-file basis instead of crawling from a single entrypoint (something that generally makes builds more efficient).

If that doesn't fix it either, can you provide a simple repository where this behavior can be observed? I'll take a look at what's going on then.

**Comment by camillobucciarelli** [comment] 2023-09-08 08:43
> Does `featureA` depend on `drift_dev` as well? That's necessary now for drift to see its members now since the analysis happens on a per-file basis instead of crawling from a single entry point (something that generally makes builds more efficient).
> 
> If that doesn't fix it either, can you provide a simple repository where this behavior can be observed? I'll take a look at what's going on then.

yes `featureA` depend on `drift_dev`.

here is a small replica [repo](https://github.com/camillobucciarelli/drift_generation_issue) I hope it is all correct, I did it faster.

The error appears if you run `melos build_runner:build `.

**Comment by simolus3** [comment] 2023-09-08 15:36
> here is a small replica [repo](https://github.com/camillobucciarelli/drift_generation_issue) I hope it is all correct, I did it faster.

The repository seems to be empty.

**Comment by camillobucciarelli** [comment] 2023-09-08 15:39
> > here is a small replica [repo](https://github.com/camillobucciarelli/drift_generation_issue) I hope it is all correct, I did it faster.
> 
> The repository seems to be empty.

sorry, check now

**Comment by simolus3** [comment] 2023-09-08 17:02
I really don't like this, but I think it's a build\_runner quirk. I was able to resolve it, but it's ugly. You need to create two files, `db.build.yaml` and `feature_a.build.yaml` in `features/db`:

```yaml
# feature_a.build.yaml
targets:
  $default: {}
  drift:
    auto_apply_builders: false
    dependencies: []
    builders:
      drift_dev:analyzer:
        enabled: true
```

Then, also create a `build.yaml` file in `db` with this content:

```yaml
# db.build.yaml
targets:
  $default:
    dependencies:
      - feature_a:drift
```

The problem is that `build_runner` refuses to run builders that claim to generate visible sources (which `drift_dev` in combination with `source_gen:combining_builder` does) outside of the root package. So in the default config, drift doesn't run on `feature_a` _at all_. Drift's default builder is a three-step pipeline, with the first two steps being responsible for finding elements relevant to drift in source files. When the last step (responsible for codegen) runs, it expects that the analyzing steps already ran. Since they didn't on `feature_a`, the last step in the main package thinks that `feature_a` doesn't define anything relevant for drift.

Luckily, drift exports the first two steps as a separate builder, and since that one doesn't claim to generate anything user-visible, it can be applied to dependent packages. The trick of introducing another target is necessary because `feature_a` depends on `db`, so they form a cycle and the order in which builders run in a cycle is undefined. That wouldn't be a problem if we were able to use the default builder thanks to the pipeline setup, but we can't. So we need to setup a special `drift` target that doesn't depend on the `db` target, and then have the `db` target depend on that. This breaks the cycle, running the analyzer on `feature_a` first and the error goes away.
We only need this hack for builds running in the `db` folder, so I can prefix the package names of the overridden builders to only apply these config files to builds happening in that directory.

I'm not a fan of that `build_runner` behavior, but that's the way it is. I don't really see a non-breaking way to fix this in drift, so I'm afraid you'd have to use this setup for every package that defines drift elements.

**Comment by camillobucciarelli** [comment] 2023-09-11 13:48
Thank you so much
