### ISSUE TITLE
Version solving fails when using moor_generator and mobx_codegen in the same project

### ISSUE THREAD

**Issue by cnsumner** [simolus3/moor#379] opened 2020-02-04 19:01 UTC
**What I was trying to do**
I'm working on an app that uses moor for it's database needs, and mobx for it's state management needs, which doesn't seem unreasonable to me.  

**What I expect to happen**
Pubspec version solving should not fail.

**What happened**
Version solving fails when using the latest versions of `moor_generator` and `mobx_codegen`.

`Because moor_generator >=2.0.1 depends on analyzer_plugin >=0.1.0 <0.3.0 and analyzer_plugin >=0.2.1 depends on analyzer >=0.35.3 <0.39.0, moor_generator >=2.0.1 requires analyzer >=0.35.3 <0.39.0 or analyzer_plugin >=0.1.0 <0.2.1.
And because analyzer_plugin >=0.1.0 <0.2.1 depends on analyzer >=0.35.3 <0.38.0, moor_generator >=2.0.1 requires analyzer >=0.35.3 <0.39.0.
Because mobx_codegen >=0.4.2 depends on build_resolvers ^1.3.2 which depends on analyzer ^0.39.0, mobx_codegen >=0.4.2 requires analyzer ^0.39.0.
Thus, mobx_codegen >=0.4.2 is incompatible with moor_generator >=2.0.1.`

**Comment by simolus3** [comment] 2020-02-04 19:43
Thanks for the report. This is a duplicate of https://github.com/simolus3/moor/issues/364#issuecomment-580141391, which also contains a workaround to fix this. In the next moor release, we will support the latest analyzer directly.

**Closed by simolus3** 2020-02-04 19:43 UTC

**Comment by cnsumner** [comment] 2020-02-04 20:05
Ah thank you, I looked around for an existing issue but somehow missed that one.
