### ISSUE TITLE
Foreign Keys not working as it should.

### ISSUE THREAD

**Issue by TanishMalho8ra** [simolus3/moor#163] opened 2019-09-26 09:20 UTC
So I'm making an workout tracking app. For the database i'm using Moor latest version and following ResoCoders tutorials. 
I have 2 tables I need to connect - Routines and their exercises. 

Following is the code for defining the tables -

```
class Routines extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get routineTitle =>
      text().customConstraint('REFERENCES exercises(routineTitle)')();
}

class Exercises extends Table {
  TextColumn get routineTitle => text()();
  TextColumn get exerciseName => text().nullable()();
}

class Workout extends Table {
  final Routine routine;
  final Exercise exercise;

  Workout({
    @required this.routine,
    @required this.exercise,
  });
}

@UseMoor(tables: [Routines, Exercises], daos: [RoutineDao, ExerciseDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      : super((FlutterQueryExecutor.inDatabaseFolder(
          path: 'db.sqlite',
          logStatements: true,
        )));
  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        beforeOpen: (db, details) async {
          await db.customStatement('PRAGMA foreign_keys = ON');
        },
      );
}
```

This is my DAO - 
```
@UseDao(tables: [Routines, Exercises])
class RoutineDao extends DatabaseAccessor<AppDatabase> with _$RoutineDaoMixin {
  final AppDatabase db;
  RoutineDao(this.db) : super(db);

  Stream<List<Workout>> get watchAllRoutines => select(routines)
      .join([
        leftOuterJoin(
          exercises,
          exercises.routineTitle.equalsExp(routines.routineTitle),
        )
      ])
      .watch()
      .map((rows) => rows.map((row) => Workout(
          routine: row.readTable(routines),
          exercise: row.readTable(exercises))));
  Future<List<Routine>> get getAllRoutines => select(routines).get();
  Future addRoutine(Insertable<Routine> routine) =>
      into(routines).insert(routine);
  Future deleteRoutine(Insertable<Routine> routine) =>
      delete(routines).delete(routine);
}
```

When I add in any routine or exercise, the Workout list is always null even if the routine and exercise have data in it. Nothing is showing on the screen and i get many debug errors. (no ui errors)

**Comment by simolus3** [comment] 2019-09-26 12:48
Thanks for the detailed description. There are two issues that might cause a problem:

- the routines table contains a reference to the exercises table, but the routines table is created first (so before the exercises table exists). Can you try to switch the order in the `@UseMoor` annotation? (e.g `tables: [Exercises, Routines]`)
- you use `routineTitle` in the reference clause, but the generated columns will use snake_case. So `REFERENCES exercises(routine_title)` should work

> and i get many debug errors

Would be good to have the error message on some of them :) If it complains about some table not existing or a violated constraint, it's probably because one of the problems above.

**Comment by simolus3** [comment] 2019-09-27 16:15
One minor problem: `Workout` shouldn't extend from table, because the workouts aren't stored as a table in sqlite (this can confuse the generator, but it's not a problem in this case).

I just tried your code locally, and I've found the problem: The "foreign key mismatch" error happens because `Exercises.routineTitle` is not unique in the `Exercises` table! This means that there could be two exercises with the same `routineName`. Now if we have a routine with the same name, which of the exercises would it reference? Sqlite just reports an error right away in that case.

There are two fixes possible here:
1. Make `Exercises.routineTitle` a primary key, which makes it unique. It would fix the error, but then each exercise can only belong to one routine, and each routine can only have one exercise. That's probably not what you want
2. To model a many-to-many relationship between routines and exercises (which means that a routine can consist of multiple exercises, and that an exercise can appear in more than one routine), you would have to introduce another table ([this article](https://dzone.com/articles/how-to-handle-a-many-to-many-relationship-in-datab) explains this quite nicely). Moor has an example on many-to-many relationships that models a shopping-card system [here](https://moor.simonbinder.eu/docs/examples/relationships/). Maybe that example helps building your workout database as well.

I'll close this issue because moor is working as intended here, but if you run into any other problems or have any questions, please let me know :)

**Closed by simolus3** 2019-09-27 16:15 UTC
