### ISSUE TITLE
 Expected exactly one element with left join

### ISSUE THREAD

**Issue by zawadZwd** [simolus3/moor#258] opened 2019-11-28 12:47 UTC
Hello Simolus3
From yesterday I'm trying to solve a small issue.
I have two tables:

> Languages 
```dart 
class Languages extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get internalId => integer()();
  IntColumn get languageId => integer()();
  TextColumn get languageName => text()();
  TextColumn get textValue => text()();
}
```

> Languages table values:
```dart 
Language(
   id: 1, 
   internalId:1, 
   languageId: 1, 
   languageName: 'polish', 
   textValue: 'wyślij'
);
```
```dart 
Language(
   id: 2, 
   internalId:2, 
   languageId: 2, 
   languageName: 'english', 
   textValue: 'submit'
);
```

> Settings table
```dart
class Settings extends Table {
  IntColumn get loginId => integer()();
}
```
> Settings table values:
```dart
Setting(id: 1);
```

>Additional class
```dart
class TestClass {
  final Language languageData;

  TestClass({this.languageData});
}
```

Now, I want to join these two tables like this:

```dart
final query = select(languages).join(
      [
        leftOuterJoin(
          settings,
          settings.loginId.equalsExp(languages.languageId),
        ),
      ],
    )..where(languages.internalId.equals(1));

    return query.watchSingle().map(
      (row) {
        return TestClass(
          languageData: row.readTable(languages),
        );
      },
    ).handleError((e) {
      throw Exception('HANDLE ERROR: $e');
    });
```

And it should ( I need to :D ) return only one row, but somehow I get all two rows from languages table :/
I thought maybe I'm trying the wrong query but in MySQL, I created two identical tables and test on a raw query and get a correct result.

Sorry for the mess in explanation, I hope you will get the point :D

**Comment by zawadZwd** [comment] 2019-11-29 08:22
Moor's generating this query:

```SQL
SELECT 	languages.id AS "languages.id", 
	languages.internal_id AS "languages.internal_id", 
        languages.language_id AS "languages.language_id", 
        languages.language_name AS "languages.language_name", 
        languages.text_value AS "languages.text_value", 
        settings.login_id AS "settings.login_id" 
FROM languages 
LEFT OUTER JOIN settings ON settings.login_id = languages.language_id 
WHERE languages.internal_id = ?; with args [1]
```

And in MySQL return one value, but in dart, it still gets me 2 rows. I can see I can't count on a response from the author of the moor, so maybe anyone else knows what it is about?

**Comment by Mike278** [comment] 2019-11-29 13:13
> I can see I can't count on a response from the author of the moor

That seems a bit inflammatory, you only reported this issue yesterday!

If MySQL is returning the correct result with the query generated by moor, then moor must be generating a correct query and the problem is likely with your data. You should check if any of your tables have duplicate entries, and consider adding unique constraints if allowing duplicates is not what you want.

**Comment by zawadZwd** [comment] 2019-11-29 14:01
> That seems a bit inflammatory,
You are right, I didn't mean to hurt anybody, my apologies :/

Thanks, I'll check your idea.

**Comment by simolus3** [comment] 2019-11-29 16:42
Issues like this require me to setup a reproduction, so it takes a bit longer to get to them.

As Mike said, it looks like there might be a problem with your data. I tried to reproduce your example by manually inserting the two languages and the one setting. I'm seeing the expected behavior though, both with `moor_ffi` and `moor_flutter`: https://pastebin.com/QXwZnt9m

**Comment by simolus3** [comment] 2020-01-26 14:52
Since I didn't found any problem in my repro, I'll close this. If you still run into this and can provide a short example that doesn't work as expected, I'll re-open the issue.

**Closed by simolus3** 2020-01-26 14:52 UTC
Labels: question
