### ISSUE TITLE
setState not updating value in copyWith

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#456] opened 2020-03-25 14:34 UTC
Not sure is this the correct place to ask.

I want to update the status value and change the icon when icon button is pressed. But the icon still remain as cloud_off since the initial value for the status is not uploading inside the moor.
```
IconButton(
              iconSize: 15,
              onPressed: _abc.status == "Uploading"
                  ? null
                  : () {
                      setState(() {
                        _abc=
                            _abc.copyWith(status: "Uploading");
                      });   
                    },
              icon: _abc.status == "Uploading"
                  ? Icon(Icons.cloud_upload, color: Colors.green, size: 15)
                  : Icon(Icons.cloud_off, color: Colors.red, size: 15))
```

**Comment by simolus3** [comment] 2020-03-25 19:37
This looks like a bug in moor. Can you post the generated `copyWith` code? Also, is `_abc` a row class or a companion class?

**Comment by tony123S** [comment] 2020-03-26 02:43
This is how I defined _abc
ABC _abc;

ABC is in .g.dart file

```
class ABC extends DataClass implements Insertable<ABC> {...
}
```

**Comment by tony123S** [comment] 2020-03-26 03:34
Below is my project video. You can see the value has changed to Uploading, but the icon still remain the same.

https://imgur.com/4tvTLPS

Here the latest code

```

IconButton(
          onPressed: _abc.status == "Uploading"
              ? null
              : () {
                  setState(() {
                    _abc= _abc.copyWith(status: "Uploading");
                    Toast.show("The value change to " + _abc.status,
                        context);
                  });
                },
          icon: _abc.status == "Uploading"
              ? Icon(Icons.cloud_upload, color: Colors.green)
              : Icon(Icons.cloud_off, color: Colors.red));


```

**Comment by simolus3** [comment] 2020-03-26 09:36
Based on that toast it looks like moor is working as intended here, but I don't see why your code wouldn't work. Are you assigning `_abc` anywhere else? You could also try to put a breakpoints in the build method and on each assignment, to see what values are present.

I'll close this as it looks like it's not a moor issue.

**Closed by simolus3** 2020-03-26 09:36 UTC

**Comment by tony123S** [comment] 2020-03-26 10:02
It keeps printing the initial value, which is Fail when icon is clicked.

 ```
Widget _showUploadStatus(ABC _abc) {
    Widget icon;
    print(_abc.status);
    if (_abc,status == "Fail") {
      icon = IconButton(
          onPressed: _abc.status == "Uploading"
              ? null
              : () {
                  setState(() {
                    _abc = _abc.copyWith(status: "Uploading");
                  });
                },
          icon: _abc.status == "Uploading"
              ? Icon(Icons.cloud_upload, color: Colors.green)
              : Icon(Icons.cloud_off, color: Colors.red));
    } else if (_abc.status == "Uploading") {
      icon = IconButton(
          onPressed: null,
          icon: Icon(
            Icons.cloud_upload,
            color: Colors.green,
          ));
    } else {
      icon = Container();
    }
    return icon;
  }
```

**Comment by tony123S** [comment] 2020-03-26 10:13
It printed

Fail, Uploading, then Fail again...

**Comment by simolus3** [comment] 2020-03-26 11:13
Uh, is `_abc` supposed to be a parameter? In that case, changing it wouldn't actually modify any state. If it's a field in the state class, there must be some other place where you're changing the value of `_abc`, otherwise it wouldn't go back to Fail.

**Comment by tony123S** [comment] 2020-03-26 11:21
Wonder can I just update the value which has been stored in moor ?

I have modified my code  as below

```
Widget icon;
 _icon = IconButton(
                onPressed: () {
                  setState(() {
                    print("Before " + _abc.status);
                    _abc = _abc.copyWith(status: "Uploading");
                    print(_abc.status);
                  });
                },
                icon: _abc.status == "Fail"
                    ? Icon(Icons.cloud_off, color: Colors.red)
                    : _abc.status == "Uploading"
                        ? Icon(Icons.cloud_upload, color: Colors.green)
                        : Container()),
```

**Comment by simolus3** [comment] 2020-03-26 14:16
If you press the button multiple times, does it get back to `Before Fail`? If so, there is another place where you assign `_abc`. Without seeing that or having more context I can't help you unfortunately.

**Comment by tony123S** [comment] 2020-03-26 14:31
It not going back to Fail
