### ISSUE TITLE
One to one relationship inner join returns null but in db we have a data

### ISSUE THREAD

**Issue by bePagani** [simolus3/moor#1713] opened 2022-02-25 10:32 UTC
hello I wrote this stream method and run in one class like this 

```dart
class ClientPolicyEntries{
  final Client client;
  final Policy? policy;

  ClientPolicyEntries(this.client, this.policy);
}
```
```dart
  Stream<List<ClientPolicyEntries>> watchEntriesInCategory() {
        final query = select(clients)
        .join([leftOuterJoin(policies, policies.holder.equalsExp(clients.id))]);
      log(query.toString());
    return query.watch().map((rows) {
      return rows.map((row) {
        return ClientPolicyEntries(
          row.readTable(clients),
          row.readTableOrNull(policies),
        );
      }).toList();
    });
  }
```
this is my table 
```dart
@UseRowClass(Policy)
class Policies extends Table {
  IntColumn get id => integer().withDefault(const Constant(0))();
  TextColumn get number => text().withDefault(const Constant(""))();
  TextColumn get signTime => text().withDefault(const Constant(""))();
  TextColumn get validFrom => text().nullable()();
  TextColumn get validTill => text().nullable()();
  IntColumn get customerId => integer().withDefault(const Constant(0))();
  TextColumn get insuranceTypeId => text().withDefault(const Constant(""))();
  IntColumn get contractTypeId => integer().withDefault(const Constant(0))();
  TextColumn get mobileNumber => text().withDefault(const Constant(""))();
  TextColumn get email => text().withDefault(const Constant(""))();
  IntColumn get notificationTypeId => integer().withDefault(const Constant(0))();
  TextColumn get promo => text().withDefault(const Constant(""))();
  TextColumn get filialId => text().withDefault(const Constant(""))();
  IntColumn get discount => integer().withDefault(const Constant(0))();
  IntColumn get holder => integer().references(Clients, #id).nullable()();
  IntColumn get drivers => integer().references(Clients, #id).nullable()();
  IntColumn get vehicles => integer().references(Vehicles, #id).nullable()();
  IntColumn get paymentType => integer().withDefault(const Constant(0))();
}
```

**Comment by bePagani** [comment] 2022-02-25 11:12
and why log statement don't print all functions I can't see full statement
<img width="1101" alt="Снимок экрана 2022-02-25 в 12 28 54" src="https://user-images.githubusercontent.com/52707370/155705616-ea018dc2-4ed0-430f-a553-ec092d51cd0a.png">
?

**Comment by simolus3** [comment] 2022-02-25 12:20
The query looks correct to me, are you sure that there is a matching row in the `policies` table?

> and why log statement don't print all functions I can't see full statement

That's a Flutter thing I believe. You can use

```dart
runZoned(
  yourAppEntrypoint,
  zoneSpecification: ZoneSpecification(
    print: (self, parent, zone, line) => debugPrint(line),
  ),
)
```

To change the `print` calls used by drift into `debugPrint`s for Flutter.

**Comment by bePagani** [comment] 2022-02-25 13:46
In initstate I make function create a row policy with default values
but holder val I got null value

**Comment by simolus3** [comment] 2022-02-25 20:32
I think I need more information to help you here. Can you pull the database from the device and check if the matching rows are there (i.e. you get results when you write the join manually)?

**Comment by bePagani** [comment] 2022-02-27 05:19
how can i do this

**Comment by bePagani** [comment] 2022-02-27 05:19
?

**Comment by simolus3** [comment] 2022-02-27 15:58
When you're constructing the `NativeDatabase` in the `LazyDatabase`, you can print the full file path. On Android, you can use `adb pull <file> file.db` to store the database as `file.db`.

**Comment by bePagani** [comment] 2022-02-27 16:01
can i do this from iphone simulator?

**Comment by bePagani** [comment] 2022-02-27 16:05
can i open for you my repository of project?

**Comment by bePagani** [comment] 2022-02-28 12:58
please can you write simmilar code and check it works?

**Comment by bePagani** [comment] 2022-02-28 12:58
because i write too much analogs and no ones works ...

**Comment by simolus3** [comment] 2022-02-28 15:37
> can i open for you my repository of project?

Sure, I can take a quick look. If you invite me, can you also describe what I need to do to reproduce this bug in your app?

**Comment by bePagani** [comment] 2022-02-28 15:39
https://github.com/bePagani/nsk.mobile/invitations
please

**Comment by bePagani** [comment] 2022-02-28 15:39
see the database model?

**Comment by bePagani** [comment] 2022-02-28 15:41
and please open the ClientPolicyEntries class see how works my relationship model 
and watch in pages policy_holder.dart class and also look the initstate

**Comment by bePagani** [comment] 2022-02-28 15:42
or can you try to make from jsonPlaceholder relationship like in documentation?

**Comment by simolus3** [comment] 2022-02-28 16:03
The problem is that you insert into `policies`, but not into `clients`. Since `policies` is the table from the outer join, it's not the relevant one. As long as there is no client, there won't be any results from the query.

From the logs, it also looks like you immediately delete all `policies` and `vehicles` when the app is opened. That may be another issue causing no rows to be visible :D

Closing this as drift appears to be working as intended.

**Closed by simolus3** 2022-02-28 16:03 UTC

**Comment by bePagani** [comment] 2022-02-28 16:08
<img width="319" alt="Снимок экрана 2022-02-28 в 22 07 02" src="https://user-images.githubusercontent.com/52707370/156017008-18f956f8-823a-43f9-a71c-5d143a2f3ce8.png">
<img width="823" alt="Снимок экрана 2022-02-28 в 22 07 45" src="https://user-images.githubusercontent.com/52707370/156017017-7579b829-9a8d-4fe6-8f9d-ef9fc7264abd.png">
<img width="613" alt="Снимок экрана 2022-02-28 в 22 07 29" src="https://user-images.githubusercontent.com/52707370/156017031-65eea211-c4fa-4ade-9651-658f3030a612.png">
<img width="339" alt="Снимок экрана 2022-02-28 в 22 07 11" src="https://user-images.githubusercontent.com/52707370/156017036-abc0dbfa-7955-4826-9d1c-2960c639dbd8.png">
<img width="348" alt="Снимок экрана 2022-02-28 в 22 07 07" src="https://user-images.githubusercontent.com/52707370/156017039-4ba4c0d4-dc65-4630-b493-31772a37baf6.png">

**Comment by bePagani** [comment] 2022-02-28 16:09
Please try make one to many function from jsonplaceholder because i make simmilar stream and i got null value
