### ISSUE TITLE
error occurred when running build_runner

### ISSUE THREAD

**Issue by aidooyaw1992** [simolus3/moor#194] opened 2019-10-17 14:11 UTC
Hi please i keep getting this error and i dont know.
this error occurred when i ran build_runner
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'

**Comment by simolus3** [comment] 2019-10-17 17:10
Can you try to re-run the builder with the `-v` flag, e.g. `flutter pub run build_runner build -v`

**Comment by aidooyaw1992** [comment] 2019-10-17 17:29
Hi, i did a flutter upgrade and the error is gone. But ive found a warning

abstract class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(const SqlTypeSystem.withDefaults(), e);  // EVALUATION OF THIS CONSTANT EXPRESSION THROWS AN EXCEPTION
  $CustomerAccountsTable _customerAccounts;
  $CustomerAccountsTable get customerAccounts =>
      _customerAccounts ??= $CustomerAccountsTable(this);
  $MetersTable _meters;
  $MetersTable get meters => _meters ??= $MetersTable(this);
  $AgentRoutesTable _agentRoutes;
  $AgentRoutesTable get agentRoutes => _agentRoutes ??= $AgentRoutesTable(this);
  $MeterReadingsTable _meterReadings;
  $MeterReadingsTable get meterReadings =>
      _meterReadings ??= $MeterReadingsTable(this);
  $VerifiedAccountsTable _verifiedAccounts;
  $VerifiedAccountsTable get verifiedAccounts =>
      _verifiedAccounts ??= $VerifiedAccountsTable(this);
  CustomerAccountsDao _customerAccountsDao;
  CustomerAccountsDao get customerAccountsDao =>
      _customerAccountsDao ??= CustomerAccountsDao(this as AppDatabase);
  MetersDao _metersDao;
  MetersDao get metersDao => _metersDao ??= MetersDao(this as AppDatabase);
  AgentRoutesDao _agentRoutesDao;
  AgentRoutesDao get agentRoutesDao =>
      _agentRoutesDao ??= AgentRoutesDao(this as AppDatabase);
  MeterReadingsDao _meterReadingsDao;
  MeterReadingsDao get meterReadingsDao =>
      _meterReadingsDao ??= MeterReadingsDao(this as AppDatabase);
  VerifiedAccountsDao _verifiedAccountsDao;
  VerifiedAccountsDao get verifiedAccountsDao =>
      _verifiedAccountsDao ??= VerifiedAccountsDao(this as AppDatabase);
  CheckAccountsTableForEntriesResult _rowToCheckAccountsTableForEntriesResult(
      QueryRow row) {
    return CheckAccountsTableForEntriesResult(
      count: row.readInt('count(*)'),
    );
  }

**Comment by simolus3** [comment] 2019-10-17 17:31
That's an analyzer bug (https://dartbug.com/38658), we generate a workaround in moor and moor_generator 2.0.1. Can you try to upgrade your packages and then run the build again?

**Comment by aidooyaw1992** [comment] 2019-10-17 23:38
Ok sure I will update and check

**Comment by aidooyaw1992** [comment] 2019-10-25 12:36
when updated, i cant even run build runner successfully

type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
package:analyzer/src/summary/link.dart 5680:5                     TypeProviderForLink._buildInterfaceType
package:analyzer/src/summary/link.dart 5645:23                    TypeProviderForLink.objectType
package:analyzer/src/summary/link.dart 926:67                     ClassElementForLink_Class._computeInterfaceType
package:analyzer/src/summary/link.dart 824:27                     ClassElementForLink_Class.supertype
package:analyzer/src/task/strong_mode.dart 303:33                 InstanceMemberInferrer._inferClass
package:analyzer/src/task/strong_mode.dart 335:9                  InstanceMemberInferrer._inferClasses
package:analyzer/src/task/strong_mode.dart 56:5                   InstanceMemberInferrer.inferCompilationUnit
package:analyzer/src/summary/link.dart 1643:7                     CompilationUnitElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3985:12                    LibraryElementInBuildUnit.link
package:analyzer/src/summary/link.dart 3685:15                    LibraryCycleNode.link
package:analyzer/src/summary/link.dart 3625:7                     LibraryCycleDependencyWalker.evaluate
package:analyzer/src/summary/link.dart 2230:13                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2196:24                    DependencyWalker.walk.strongConnect
package:analyzer/src/summary/link.dart 2249:18                    DependencyWalker.walk
package:analyzer/src/summary/link.dart 3658:42                    LibraryCycleForLink.ensureLinked
package:analyzer/src/summary/link.dart 4190:35                    Linker.link
package:analyzer/src/summary/link.dart 312:74                     _relink
package:analyzer/src/summary/link.dart 126:3                      link
package:analyzer/src/dart/analysis/library_context.dart 220:25    LibraryContext.load.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/library_context.dart 219:12    LibraryContext.load
package:analyzer/src/dart/analysis/library_context.dart 98:7      new LibraryContext
package:analyzer/src/dart/analysis/driver.dart 1439:29            AnalysisDriver._createLibraryContext
package:analyzer/src/dart/analysis/driver.dart 1380:28            AnalysisDriver._computeUnitElement.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/driver.dart 1378:20            AnalysisDriver._computeUnitElement
package:analyzer/src/dart/analysis/driver.dart 997:34             AnalysisDriver.performWork
package:analyzer/src/dart/analysis/driver.dart 1931:24            AnalysisDriverScheduler._run
package:analyzer/src/dart/analysis/driver.dart 1865:5             AnalysisDriverScheduler.start
package:build_resolvers/src/analysis_driver.dart 54:13            analysisDriver
package:build_resolvers/src/resolver.dart 138:18                  new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 193:19        BuildOptions.create
package:build_runner/src/generate/build.dart 85:36                build
package:build_runner/src/entrypoint/build.dart 28:24              BuildCommand.run
package:args/command_runner.dart 197:27                           CommandRunner.runCommand
package:args/command_runner.dart 112:25                           CommandRunner.run.<fn>
dart:async                                                        new Future.sync
package:args/command_runner.dart 112:14                           CommandRunner.run
package:build_runner/src/entrypoint/run.dart 24:31                run
.dart_tool\build\entrypoint\build.dart 22:22                      main

**Comment by aidooyaw1992** [comment] 2019-10-25 12:45
please im using moor_flutter

**Comment by simolus3** [comment] 2019-10-25 14:17
This sounds like a (fixed) bug in the build package, see for example https://github.com/dart-lang/build/issues/2478.

Can you try to run `flutter packages upgrade` again? If it still doesn't work, can you post the snippet of the `pubspec.lock` file for the build_resolvers package (it's a transitive dependency).

**Comment by aidooyaw1992** [comment] 2019-10-25 16:10
it worked when i switched to flutter channel stable

**Comment by simolus3** [comment] 2019-10-25 18:04
Thanks for trying it out. It's bad that it only works on stable of course, but I'll close this as it's not a bug in moor, and rather one in one of the build packages. If you can consistently reproduce this, I'd recommend filing a bug on [this repo](https://github.com/dart-lang/build/) and including the exact Flutter version as well as the relevant parts from `pubspec.lock`.

**Closed by simolus3** 2019-10-25 18:04 UTC

**Comment by aidooyaw1992** [comment] 2019-10-26 20:11
Ok sure
