### ISSUE TITLE
type 'AppSettingsTable' is not a subtype of type 'TableInfo<Table, DataClass>' of 't'

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#283] opened 2019-12-17 21:29 UTC
After upgrading to the latest Dart/Flutter, our CI started failing with the following error:

```
2 errors, see stacktrace for details
Error #1: type 'AppSettingsTable' is not a subtype of type 'TableInfo<Table, DataClass>' of 't'\n\nStacktrace:
package:moor/src/runtime/executor/stream_queries.dart         StreamQueryStore.handleTableUpdates.<fn>
dart:core                                                     Iterable.toSet
package:moor/src/runtime/executor/stream_queries.dart 106:67  StreamQueryStore.handleTableUpdates
package:moor/src/runtime/database.dart 220:34                 QueryEngine._customWrite
\n\n\nError #2: Unimplemented handling of missing static target\n\nStacktrace:
dart:async                            _AsyncAwaitCompleter.start
test/app/app_manager_test.dart 51:12  main.<fn>
```
All the tests in `app_manager_test.dart` failed with this error, yet other tests that hit the `AppSettingsTable` work fine. I managed to fix it by aliasing one of the imports in that file (i.e change `import 'package:my_app/data/some_api.dart';` -> `import 'package:my_app/data/some_api.dart'; as r`), but after removing the `as r` I can no longer reproduce the failure!

Current theory is that there was some weird caching going on related to the Dart/Flutter upgrades, because it was only happening on some machines. Have you seen anything like this before?

**Comment by simolus3** [comment] 2019-12-17 22:11
> Have you seen anything like this before?

Uh, no... That's sounds like a very bizarre bug somewhere in the Dart compiler, especially that "Unimplemented handling of missing static target" sounds weird. By a quick look, this is thrown by the VM when a static method [doesn't exist](https://github.com/dart-lang/sdk/blob/f2618b0077441662aeb2d26687f670c745f8ddda/runtime/vm/compiler/frontend/kernel_translation_helper.cc#L528-L529). Again, very weird that this is happening in an internal class of the Dart SDK (`_AsyncAwaitCompleter.start`).

As you said, this kind of sounds like a cache problem, but I don't know enough about the Dart compiler frontend to say that with confidence.

I'll close this since it likely isn't a moor issue. It might make sense to open an issue on Flutter or the Dart SDK if this happens again. Though I imagine it can be hard to reproduce.

**Closed by simolus3** 2019-12-17 22:11 UTC

**Comment by Mike278** [comment] 2019-12-18 13:35
Alright thanks for taking a look, appreciate it! I'll definitely file a Dart SDK issue if I'm able to reproduce it.
