### ISSUE TITLE
Required field with autoIncrement

### ISSUE THREAD

**Issue by krunduev** [simolus3/moor#1605] opened 2021-12-28 08:48 UTC
For
```
class Employees extends Table {
  IntColumn get id => integer().autoIncrement()();
```
I have generated
```
  Employee(
      {required this.id,
```
so I cant' create and insert Employee because id is required but before insert is unknown

  moor_generator: ^4.6.0+1

**Comment by simolus3** [comment] 2021-12-28 11:04
As @kuhnroyal said, you'll have to use `EmployeesCompanion.insert` to insert a row.

Basically, moor/drift will generate two classes for a table:

- The `Employee` data class, holding a complete row of the `Employees` table. If `id` wasn't required, we'd have to make it nullable which would be annoying for selects where you know the `id` is not null.
- The `EmployeesCompanion` class, which represents _partial_ data. This can be useful to update certain fields in an `UPDATE` or to write inserts where some fields have default values or are auto-generated.

This is also explained [in the docs](https://drift.simonbinder.eu/docs/getting-started/writing_queries/#updates-and-deletes). I'm closing this since it's working as intended.

**Closed by simolus3** 2021-12-28 11:04 UTC
