### ISSUE TITLE
[moor_ffi] Filter for Boolean fields is not properly translated on armeabi-v7a devices

### ISSUE THREAD

**Issue by loomp** [simolus3/moor#671] opened 2020-07-01 14:08 UTC
Hello,

Finally, I have found a problem after acquiring armeabi-v7a device (Alcatel 1B) to test weird behavior on these specific devices.
Not sure if this is strictly moor_ffi package issue or dart.

Filters on Boolean fields seem to be not translated to 0/1 integers on armeabi-v7a devices in RELEASE, all other architectures work fine.
Debug works fine, but RELEASE provides errors.

Table:
```
class MenuTable extends AppTable {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().nullable()();
  TextColumn get category => text().nullable()();
  BoolColumn get active => boolean().nullable()();
  TextColumn get subtitle => text().nullable()();
  TextColumn get path => text().nullable()();
  TextColumn get object => text().nullable()();
  TextColumn get route => text().nullable()();
  TextColumn get tabs => text().map(const ListConverter()).nullable()();
  TextColumn get data => text().map(const MapConverter()).nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
```

Snippet:
```
    final test = await (select(menuTable).get());
    print('all menus: ' + test.length.toString());

    final data = await (select(menuTable)
      ..where((table) => table.active.equals(true))).get();

    print('filtered menus: ' + data.length.toString());
```

Results (armeabi-v7a -> RELEASE):
```
I/flutter ( 7153): all menus: 140
I/flutter ( 7153): filtered menus: 0
```

Results (armeabi-v7a -> DEBUG, or any other architectures (i.e. arm64-v8a)):
```
I/flutter ( 7153): all menus: 140
I/flutter ( 7153): filtered menus: 137
```

The database:
![image](https://user-images.githubusercontent.com/59165289/86253538-fb216a80-bbb4-11ea-926d-7d7e66eb0893.png)

Doctor:
```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.5 at e:\SDK\flutter
    • Framework revision 8af6b2f038 (18 hours ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mariu\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.0

[√] Connected device (1 available)
    • 5002D EEA • e89e0665 • android-arm • Android 10 (API 29)

• No issues found!
```

**Comment by simolus3** [comment] 2020-07-01 14:29
This is a bug in the Dart compiler (https://github.com/flutter/flutter/issues/54948). We bind booleans as 64-bit ints. For those, Flutter apps built on Windows mistakenly switch the upper and lower 32 bits when targeting armv7 devices. So when we want to write `true = 0x1`, we actually write `0x1 0000 0000`, which causes the error.

I'll close this as a duplicate of #446. It should work when you build your app on another OS or use a non-stable Flutter channel. If that still doesn't work, please comment on the Flutter issue to share your setup.

**Closed by simolus3** 2020-07-01 14:29 UTC
