### ISSUE TITLE
Select on tables do not return insertion order, rather PK (id) order

### ISSUE THREAD

**Issue by rubenferreira97** [simolus3/moor#845] opened 2020-10-01 18:59 UTC
Hi, is there any way to select rows ordered by insertion order? After testing I found that the query select(table) returns the rows ordered by id.

**Comment by simolus3** [comment] 2020-10-01 19:34
In sqlite, the order of returned rows is undefined if you don't use an explicit `ORDER BY` clause. They just happen to be ordered by their rowid (or `INTEGER PRIMARY KEY` column) by default.

> is there any way to select rows ordered by insertion order

Usually, that's what should happen if you have an auto-incrementing integer column. If you have a custom primary key that's also an int, you'd have to add another int column to track the insertion order.

You could use `DateTimeColumn createdAt => dateTime().default(currentDateAndTime)()` and then sort by that.

**Comment by rubenferreira97** [comment] 2020-10-01 23:17
I have inserted the rows in this order (id:45, title: "Category1"), (id:44, title: "Category2"), ..., (id:40, title:"Category6") in a batch. However when I make a select 40, 41,... 46 is returned. I don't think this is a normal behavior.

**Comment by simolus3** [comment] 2020-10-02 07:03
Yes it is. From the [sqlite3 documentation](https://www.sqlite.org/lang_select.html#orderby):

> If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined

So any order for the select is normal behavior if you don't set an explicit `ORDER BY`.

If sqlite3 preserved the insertion order, it would have to store additional data so one can argue that it shouldn't do that by default. If you want to sort by insertion order, you would have to add your own incrementing column in Dart. I'll close this issue since moor behaves as intended, but I can help you add that column if you want to.

**Closed by simolus3** 2020-10-02 07:03 UTC
