### ISSUE TITLE
Add column error while migrating

### ISSUE THREAD

**Issue by T-Oner** [simolus3/moor#1633] opened 2022-01-15 10:26 UTC
sqlite exec result is `SqliteException(1): SQL logic error   Causing statement:  ALTER TABLE categories ADD COLUMN pomo_enabled INTEGER NOT NULL DEFAULT 0 CHECK (pomo_enabled IN (0, 1));`. But the sql is right.

# Code:

### Table

```dart
@DataClassName('Category')
class Categories extends Table {
  TextColumn get sid => text()();

  BoolColumn get pomoEnabled => boolean().withDefault(const Constant(false))();

}
```

### Migration

```dart
await m.addColumn(db.categories, db.categories.pomoEnabled);
```

### error log

```log
E/flutter (31478): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SqliteException(1): SQL logic error
E/flutter (31478):   Causing statement: ALTER TABLE categories ADD COLUMN pomo_enabled INTEGER NOT NULL DEFAULT 0 CHECK (pomo_enabled IN (0, 1));
E/flutter (31478): #0      DatabaseImpl.execute (package:sqlite3/src/impl/database.dart:129:9)
E/flutter (31478): #1      _VmDelegate._runWithArgs (package:drift/src/ffi/database.dart:204:11)
E/flutter (31478): #2      _VmDelegate.runCustom (package:drift/src/ffi/database.dart:214:11)
E/flutter (31478): #3      _BaseExecutor.runCustom.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:109:19)
E/flutter (31478): #4      _BaseExecutor._synchronized.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:51:22)
E/flutter (31478): #5      new Future.sync (dart:async/future.dart:296:31)
E/flutter (31478): #6      Lock.synchronized.callBlockAndComplete (package:drift/src/utils/synchronized.dart:17:21)
E/flutter (31478): #7      Lock.synchronized.<anonymous closure> (package:drift/src/utils/synchronized.dart:21:35)
E/flutter (31478): #8      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter (31478): #9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (31478): <asynchronous suspension>
E/flutter (31478): #10     migration9to10.<anonymous closure>.<anonymous closure> (package:timez/src/data/db/migrations/migration_9_10.dart:8:7)
E/flutter (31478): <asynchronous suspension>
E/flutter (31478): #11     DatabaseConnectionUser.transaction.<anonymous closure>.<anonymous closure> (package:drift/src/runtime/api/connection_user.dart:438:26)
E/flutter (31478): <asynchronous suspension>
E/flutter (31478): #12     DatabaseConnectionUser.transaction (package:drift/src/runtime/api/connection_user.dart:431:12)
E/flutter (31478): <asynchronous suspension>
```

# lib

```yml
  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.0
```

**Comment by T-Oner** [comment] 2022-01-15 10:47
It seems sqlite not support `CHECK`. When i remove the `CHECK (pomo_ask_before IN (0, 1))`, everything works fine.

**Comment by simolus3** [comment] 2022-01-15 13:56
I couldn't reproduce this issue locally. The same `ALTER` statement with the `CHECK` works fine for me. We're also generating `CHECK` in `CREATE TABLE` statements, so I don't think it's about that probably.

Can you the exact version of `sqlite3_flutter_libs` that you're using (take a look in `pubspec.lock`)?

**Comment by T-Oner** [comment] 2022-01-16 09:37
@simolus3 
```ymal
  sqlite3_flutter_libs:
    dependency: "direct main"
    description:
      name: sqlite3_flutter_libs
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.5.3"
```

**Comment by T-Oner** [comment] 2022-01-16 10:43
I created a new Demo project and can still reproduce the problem.

Demo: https://github.com/T-Oner/drift_debug/

Branch v1 is database version 1, branch v2 is database version 2

**Comment by simolus3** [comment] 2022-01-16 12:46
Thank you for the helpful repro! Previously I've only tested this with the default sqlite3 coming with my OS, but I can reproduce this with the compile-time options used by `sqlite3_flutter_libs`.

After some trial and error, I've found that the `SQLITE_DQS=0` compile-option (which is recommended by sqlite3) is causing this. I don't really understand why, so I've asked in [the forum](https://sqlite.org/forum/forumpost/6224011cf2). Let's see if this is a sqlite3 bug or if I'm overlooking something that would need to be changed in drfit.

**Comment by AlexITMS** [comment] 2022-01-16 12:51
I could be way off here, but in the past when modifying sqlite tables adding new fields (not drift specific), sqlite only allowed new fields to be added at the end of the field list, shuffling fields around the only way I could do it reliably was to rename the table, create a new table with the existing name and the new field structure and then copy the data across, this was a few years back so this may not be a problem anymore and may not be related to this issue. Sorry if it is unrelated.

**Comment by simolus3** [comment] 2022-01-16 17:25
Congrats, it looks like you [found a bug in sqlite3](https://sqlite.org/forum/forumpost/9719f094e4ae0360)! This is only the second time I've seen this happen, sqlite3 is remarkably stable.

I will close this issue as it's not a bug in drift.

> sqlite only allowed new fields to be added at the end of the field list

Right but isn't that what `ADD COLUMN` is doing? It doesn't look like this is about ordering.

**Closed by simolus3** 2022-01-16 17:25 UTC
