### ISSUE TITLE
spellfix1 generation not working

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2165] opened 2022-11-22 06:32 UTC
It's happening right now on develop.

Table definition:
`CREATE VIRTUAL TABLE place_spellfix USING spellfix1;`

build.yaml:
```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          skip_verification_code: true
          data_class_to_companions: false
          named_parameters: true
          generate_connect_constructor: true
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
                - spellfix1
                - rtree
```

Output:
```bash
[INFO] Running build...
[WARNING] drift_dev on lib/database/tables.drift:
Error reading table from internal statement
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
Could not analyze DriftElementId(package:search_db/database/tables.drift, place_spellfix)
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
Error reading table from internal statement
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
Could not analze DriftElementId(package:search_db/database/tables.drift, place_spellfix)
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
Error reading table from internal statement
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
Could not analze DriftElementId(package:search_db/database/tables.drift, place_spellfix)
Could not read table schema: Unknown module "spellfix1", did you register it?
[WARNING] drift_dev on lib/database/tables.drift:
line 45, column 22: The structure of this table could not be extracted, possibly due to a bug in drift_dev.
   ╷
45 │ CREATE VIRTUAL TABLE place_spellfix USING spellfix1;
   │                      ^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/database/tables.drift:
line 48, column 17: The referenced element could not be analyzed due to a bug in drift.
   ╷
48 │     INSERT INTO place_spellfix(word, langid, rank)
   │                 ^^^^^^^^^^^^^^
   ╵
[WARNING] drift_dev on lib/database/tables.drift:
line 196, column 5: The referenced element could not be analyzed due to a bug in drift.
    ╷
196 │     place_spellfix ps
    │     ^^^^^^^^^^^^^^^^^
    ╵
```

I dug into the code but couldn't find anything obvious. Fts5 and rtree modules are working flawless.

**Comment by simolus3** [comment] 2022-11-22 19:07
Thanks for the report! The issue is that the new analyzer forgot to register the spellfix1 extension. This is fixed in 59d347adbe9db890a42965ddd0a3ea2d26b49449, I've also added some checks to avoid the error being reported three times.

**Closed as completed by simolus3** 2022-11-22 19:07 UTC
Labels: bug
