### ISSUE TITLE
Flutter tells me the table has been created but omits the error as the table isn't actually created

### ISSUE THREAD

**Issue by urbanmania** [simolus3/moor#661] opened 2020-06-24 22:17 UTC
Perhaps I'm simply not seeing what I'm doing wrong so please let me know if that is the case, but the app stops creating tables when it hits this one:

```dart
class Traits extends Table {
  TextColumn get competitionTitle => text()();
  IntColumn get order => integer()();
  RealColumn get grade => real()();
  RealColumn get weight => real()();

  @override
  Set<Column> get primaryKey => {competitionTitle, order};
}
```

I have another class that does also have a primary key and not an auto incremented ID, but this doesn't get created.

**Comment by simolus3** [comment] 2020-06-25 18:06
Thanks for the report, this is indeed a bug and I was able to reproduce it. The issue is that `order` is a reserved keyword in sql, so it needs to be escaped. Moor already does this in the column definition, but failed to do so when writing the primary key.
This will be fixed in the next update. If you need a workaround before that, you could use `order => integer().named('order_')()` to change the name in sql.

I couldn't reproduce the other problem with the silent error though. With the table definition you posted, I got an exception as the database was opened.

**Comment by urbanmania** [comment] 2020-06-25 21:16
You don't know how glad I am to hear that it wasn't just me being stupid :)  I'll just rename it for my app for now, not a problem at all on my side but glad it will be fixed.

**Comment by simolus3** [comment] 2020-06-26 10:28
Great! I'll close this issue then, but if you find a repro for the silent error I'd be happy to look into that as well :)

**Closed by simolus3** 2020-06-26 10:28 UTC
