### ISSUE TITLE
GroupBy DateTime month not working as expected

### ISSUE THREAD

**Issue by seidellu** [simolus3/moor#3124] opened 2024-07-30 22:19 UTC
Many thanks for the great framework.  
Is the following a desired behavior or am I misunderstanding the usage? When I group the table rows by the month value of their date column and compute a sum over other columns I encounter the following problem:

If the date falls on the first or second of a month, it is grouped with the entries from the previous month. 

I encountered the same problem using `filter: items.date.month.equals(month))`. When using `items.date.isBetweenValues(start, end)` the problem does not occur (start== first of month 00:00:00.000, end == last of month 23:59:99.999). 

I used a Pixel 6 with API34 as an emulator for the app and the following minimal example. Drift version 2.15.0.
Expected result by minimal example: `{1: 100.0, 2: 200.0}`
Current result by minimal example: `{1: 200.0, 2: 100.0}`

```Dart
import 'dart:io';
import 'package:flutter/widgets.dart' hide Table;
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

part 'minimal_example_bug.g.dart';

@UseRowClass(Item)
class Items extends Table {
  IntColumn get id => integer().autoIncrement()();
  RealColumn get amount => real()();
  DateTimeColumn get date => dateTime()();
}

class Item {
  final int id;
  final double amount;
  final DateTime date;

  Item({
    required this.id,
    required this.amount,
    required this.date,
  });
}

@DriftDatabase(tables: [Items])
class Example extends _$Example {
  Example._internal() : super(_openConnection());

  //Namedconstructor for creating in-memory database for testing queries
  Example.forTesting(super.e);

  static Example _instance = Example._internal();

  factory Example() {
    return _instance;
  }

  @override
  int get schemaVersion => 1;

  Future<int> addItem(
    double amount,
    DateTime date,
  ) async {
    final itemToAdd = ItemsCompanion(
      amount: Value(amount),
      date: Value(date),
    );
    return into(items).insert(mode: InsertMode.insertOrAbort, itemToAdd);
  }

  Future<Map<int, double>> getMonthlyBalance(int year) async {
    Map<int, double> monthlyBalance = {};
    final balance = items.amount.sum(filter: items.date.year.equals(year));
    final query = selectOnly(items);
    query
      ..addColumns([items.date.month, balance])
      ..groupBy([items.date.month]);
    final result = await query.get();
    for (var row in result) {
      monthlyBalance[row.read<int>(items.date.month)!] =
          row.read<double>(balance) ?? 0.0;
    }
    return monthlyBalance;
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'example.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final db = Example();

  await db.addItem(100.0, DateTime(2024, 1, 8));
  await db.addItem(100.0, DateTime(2024, 2, 1));
  await db.addItem(100.0, DateTime(2024, 2, 3));

  final balance = await db.getMonthlyBalance(2024);
  print(balance);
}
```

**Comment by simolus3** [comment] 2024-07-31 19:47
Thanks for the helpful report! I think this is a timezone issue (the problem doesn't happen with `DateTime.utc` being used when inserting), but I think the local offsets should cancel out...

**Comment by simolus3** [comment] 2024-07-31 20:00
Ok, figured it out! The problem is indeed related to timezones. I'll use mine (`Europe/Berlin`) as an example to explain. By default, drift stores date time values as unix timestamps. In my timezone, 2024-02-01 had a +1 hour offset from UTC. While the timestamp is thus `1706742000` (which, for this purpose, we can consider to uniquely represent an instant in time), assigning a date or time to that timestamp requires the context of a timezone.

Unfortunately, `.month` interprets the timestamp as UTC, as [the documentation](https://drift.simonbinder.eu/api/drift/datetimeexpressions/month) also mentions. Due to the one hour offset, `1706742000` in UTC however is `2024-01-31 23:00:00` (`DateTime`s are always times, so not specifying any time would be midnight). So `moth` "correctly" identifies the date as being in January.

The docs suggest this rather clumsy workaround, which would give you the correct results:

```dart
final month = items.date.modify(DateTimeModifier.localTime()).month;
```

A better option is to [store date time values as text](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#datetime-options), because that will always include the timezone. For values stored as text, `month` behaves correctly out of the box.
Changing the option unfortunately requires a schema change and a migration since existing values need to be transformed, but the documentation section I've linked explains how to do that.

I'll close this as it is (unfortunately) working as intended. We should have been storing date times as text to begin with, but can't change the default without breaking existing databases.

**Closed as completed by simolus3** 2024-07-31 20:00 UTC
