### ISSUE TITLE
Row too big to fit into CursorWindow requiredPos=0, totalRows=1

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#1083] opened 2021-03-10 09:58 UTC
What is wrong ? Data too large?

```
W/CursorWindow(27628): Window is full: requested allocation 3095146 bytes, free space 2096676 bytes, window size 2097152 bytes
E/SQLiteQuery(27628): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM defect_description_table;
E/flutter (27628): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=1) sql 'SELECT * FROM defect_description_table;' args []}

```

Insert code

```
Future getSelectedCategory(
      BuildContext context, String urls, String accessToken) async {
    List<CategoryTableData> list = List<CategoryTableData>();
    CategoryTableData categoryData = CategoryTableData();
    try {
      var defectDescription = List<DefectDescriptionTableData>();
      var headers = {
        'authorization': "Bearer" + " " + accessToken,
        "Accept": "application/json"
      };
      var url = xxx;
      var response = await http.get(url, headers: headers);
      var res = json.decode(response.body);
      for (var i in res) {
        if (i['name'] == "Defect Descriptions") {
          defectDescription.add(DefectDescriptionTableData(
              id: i['id'], name: i['name'], data: i['data']));
        }
      }
      await dao.batch((b) {
        b.insertAll(_dao.defectDescriptionTable, defectDescription);
      });
      categoryData = await _dao.selectAllCategories();
      return categoryData;
    } catch (e) {
      print(e);
      categoryData = await _dao.selectAllCategories();
      return categoryData;
    }
  }
```

**Comment by simolus3** [comment] 2021-03-10 10:45
The problem appears to happen in a select, not in the insert. Do you store large data and blobs in `defect_description_table`? The row appears to be almost 3 MiB in size.

You could see [this StackOverflow question](https://stackoverflow.com/a/57109330/3260197) for some ideas on how to solve this. I can try to help as well if you share more details about your setup, but it sounds like this is not caused by moor so I'm going to close this.

**Closed by simolus3** 2021-03-10 10:45 UTC

**Comment by tony123S** [comment] 2021-03-10 11:04
Not blobs,only Json.
 
Here the json structure

`[{ "id": 1, "name": "Descriptions","data": [{..},{...} ... ]}]`

I think the issue is on the data list,because it contains lot of data. 

Can you tell me how to solve ? Thanks.

**Comment by tony123S** [comment] 2021-03-10 12:20
I check data length column, it has 10298.  Is it too large?

**Comment by tony123S** [comment] 2021-03-11 04:22
I keep hitting this annoying message !

When data finished insert into local database, I saw this message

`JNI critical lock held for 30.083ms on Thread[27,tid=23883,Runnable,Thread*=0xce150a00,peer=0x12cc0190,"Sqflite"]`

If I select data from the table, I get
```

W/CursorWindow(23809): Window is full: requested allocation 3095146 bytes, free space 2096696 bytes, window size 2097152 bytes
E/SQLiteQuery(23809): exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT * FROM description_table;
I/flutter (23809): DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=1) sql 'SELECT * FROM defect_description_table;' args []}
```
