### ISSUE TITLE
Slow editing of database related code when generated file is too large.

### ISSUE THREAD

**Issue by ziakhan110** [simolus3/moor#923] opened 2020-11-18 11:35 UTC
I have 21 tables in my flutter app, the generated file for moor has 12884 lines of code. Problem is when i am writing queries or doing anything related to database , android studio becomes very slow and after some time its memory usage gets very high and it shows dialog to shutdown Android Studio.
Its the same on VSCode as well.
How can i fix this problem? Is there any way to split generated file to multiple files?
<img width="349" alt="Screenshot 2020-11-18 at 4 30 40 PM" src="https://user-images.githubusercontent.com/8199129/99525708-02a6ac00-29bc-11eb-9fa8-4730eb7377ab.png">

**Comment by PiN73** [comment] 2020-11-18 11:39
https://moor.simonbinder.eu/docs/advanced-features/daos/

**Comment by ziakhan110** [comment] 2020-11-18 11:50
Is there a way to create each table class in separate file?

**Comment by Mike278** [comment] 2020-11-18 12:04
DAOs only help with splitting up queries. See #490. 

We're also seeing performance issues. Our .g.dart file has grown to 25k lines and is starting to cause serious analyzer slowness (autocompletion, lints etc). I've been meaning to spend some time investigating but it hasn't become annoying enough yet 😆

**Comment by ziakhan110** [comment] 2020-11-18 13:17
Its really hard to write any code now.

**Comment by simolus3** [comment] 2020-11-18 20:53
I'll close this as a duplicate of #490.

It probably doesn't help too much, but you can reduce the amount of generated code by enabling the `skip_verification_code` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/). Disabling `data_class_to_companions` might help too if you're not using that feature.

**Closed by simolus3** 2020-11-18 20:53 UTC
