### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ConnectionClosedException'

### ISSUE THREAD

**Issue by JerContact** [simolus3/moor#2126] opened 2022-11-05 05:15 UTC
I'm getting this error when doing these calls in quick succession:

This is the class being called:

```
DatabaseConnection createDriftIsolateAndConnect() {
  return DatabaseConnection.delayed(Future.sync(
    () async {
      //driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
      final myIsolate = await createDriftIsolate();
      return await myIsolate.connect();
    },
  ));
}

class MyDriftClass {
  ManualDatabase myDatabase =
      ManualDatabase.connect(createDriftIsolateAndConnect());
  MyDriftClass();

  Future<void> close() async {
    await myDatabase.close();
  }

  startup() {
    myDatabase = ManualDatabase.connect(createDriftIsolateAndConnect());
  }
}
```

And this is when it's called:

```
await Provider.of<MyDriftClass>(context, listen: false).close();
    await Provider.of<MyDriftClass>(context, listen: false).startup();
    Provider.of<MyDriftClass>(context, listen: false)
        .myDatabase
        .getFTS(realString)
        .get()
        .then((value) => setState(() {
              _hitsList =
                  value.map((e) => SearchHit(e.filename, e.filePath)).toList();
              stopwatch.stop();
              print(stopwatch.elapsed);

              _visible = true;
            }));
```

Not sure if it's the background isolate or what is going on, full error

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ConnectionClosedException'
#0      DriftCommunication.request
package:drift/…/remote/communication.dart:109
#1      _BaseExecutor._runRequest
package:drift/…/remote/client_impl.dart:73
#2      _BaseExecutor.runSelect
package:drift/…/remote/client_impl.dart:106
#3      LazyDatabase.runSelect
package:drift/…/utils/lazy_database.dart:83
#4      CustomSelectStatement._executeRaw.<anonymous closure>
package:drift/…/select/custom_select.dart:51
#5      DatabaseConnectionUser.doWhenOpened.<anonymous closure>
package:drift/…/api/connection_user.dart:156
<asynchronous suspension>
```

**Comment by JerContact** [comment] 2022-11-05 06:11
I even tried adding to shutdownall isolates in the background:

```
class MyDriftClass {
  DriftIsolate myIsolate;
  DatabaseConnection myDatabaseConnection;
  ManualDatabase myDatabase;
  MyDriftClass(this.myIsolate, this.myDatabaseConnection, this.myDatabase);

  Future<void> closeIsolates() async {
    await myIsolate.shutdownAll();
  }

  Future<void> close() async {
    await myDatabase.close();
    await closeIsolates();
  }

  Future<void> startup() async {
    myIsolate = await createDriftIsolate();
    myDatabaseConnection = await myIsolate.connect();

    myDatabase = ManualDatabase.connect(myDatabaseConnection);
  }
}
```

But I get the same error

**Comment by simolus3** [comment] 2022-11-05 14:13
Drift throws a `ConnectionClosedException` for pending operations to the isolate when the connection is closed.

Do you have a chance to see the statement being executed when the `ConnectionClosedException` is thrown? Do you think this could be a query stream being listened to? If you properly close the database (and it looks like you do), this shouldn't happen.

**Comment by JerContact** [comment] 2022-11-05 14:44
This is what is the next line on the error:

```
#5      _SqlHomePage._getSearchResult
package:flutter_playground/screens/drift_sql_page.dart:71
<asynchronous suspension>
```

And it is having a problem with this line:

```
final myList = await Provider.of<MyDriftClass>(context, listen: false)
        .myDatabase
        .getFTS(realString)
        .get();
```

This is happening with a type as you go search (which is what my app is doing, so each time the user types there is a new query, and since the new letter is more up-to-date, i want to kill the old query), so these 3 lines are being called somtimes in very quick succession:

```
await Provider.of<MyDriftClass>(context, listen: false).close();
    await Provider.of<MyDriftClass>(context, listen: false).startup();
    final myList = await Provider.of<MyDriftClass>(context, listen: false)
        .myDatabase
        .getFTS(realString)
        .get();
```

**Comment by simolus3** [comment] 2022-11-06 00:10
After your comment in the discussion, I think I understand what's happening now:

1. You're making a search request for the type-as-you-go search to the database.
2. Almost immediately afterwards, you're closing the database.
3. The database request is still pending and gets completed with the exception now.

I actually think the error is drift working as intended here. We could make `close()` on the database wait for outstanding operations, but that's somewhat expensive. So you get the error, but at least drift doesn't do anything stupid like never resolving the future because the connection is dead. I think the best way to solve this is to not open a new drift database for every query. If  you really want to do that, wait for all pending operations to be completed before closing the database.

**Closed as not planned by simolus3** 2022-11-06 00:10 UTC

**Comment by JerContact** [comment] 2022-11-06 06:30
That's the problem though, I can't wait, it's too slow.  To wait for each time a search gets slowed down (b/c it's a weird query with one letter) even though the user types another letter and the search needs to be updated accordingly, doesn't make sense, you know what I mean?

If the user types:

"soft i"

Then, updates while the search is still going to:

"soft image"

I don't need that "soft i" search anymore, I need it updated and for the old search to just be cancelled or elegantly not brought back.

There has to be a way to cancel all drift isolates or tell the return to just come back with nothing, or at least some return that could then be worked with accordingly.

To just say wait for the isolate doesn't seem like a good solution to this issue.  That's the whole problem, it's sometimes too slow.

If there is no fix to be had, is there a way to elegantly not get this error?  Or, in other words, is this error really that important?

**Comment by simolus3** [comment] 2022-11-06 12:54
That's fair, I think you can just manually kill the isolate in that case. 

> or tell the return to just come back with nothing, or at least some return that could then be worked with accordingly.

I still think the error is warranted, you may want to just catch and ignore it then?

```dart
final myList = await Provider.of<MyDriftClass>(context, listen: false)
        .myDatabase
        .getFTS(realString)
        .onError((error, trace) {
           // potentially log it?
           return const [];
         })
        .get();

```

-----

>  To wait for each time a search gets slowed down (b/c it's a weird query with one letter)

Somewhat off-topic, but do you have a `LIMIT` or something in that query to maybe improve performance? Even generic searches shouldn't take that long.

**Comment by JerContact** [comment] 2022-11-06 14:47
The error check works great!  How would I kill the isolate manually?

Yep, I'm limiting it to 250 right now. But I'm dealing with about 3 million rows to search through, so sometimes it takes over a second depending on the search (if you use a letter that is in a lot of searches like "big* AND s*" or "big* AND r*").

**Comment by simolus3** [comment] 2022-11-06 17:01
If you manually spawn the drift isolate (by calling `Isolate.spawn` somewhere), you're getting an `Isolate` object back which you can later kill by simply calling [`kill()`](https://api.dart.dev/stable/2.18.4/dart-isolate/Isolate/kill.html).

**Comment by JerContact** [comment] 2022-11-09 16:56
In the above example:

```
final myList = await Provider.of<MyDriftClass>(context, listen: false)
        .myDatabase
        .getFTS(realString)
        .onError((error, trace) {
           // potentially log it?
           return const [];
         }
        .get();
```

Do you know if the isolate completes properly in this case?  I'm noticing hot reload taking super long times and I'm thinking it has to do with isolates in some way

**Comment by simolus3** [comment] 2022-11-09 17:13
If you don't explicitly kill or shutdown the isolate, it will still be running. You can also view active isolates in the debugger or DevTools.
