### ISSUE TITLE
`insertOnConflictUpdate` exception on Android 10 and below

### ISSUE THREAD

**Issue by daniloapr** [simolus3/moor#1929] opened 2022-07-15 14:25 UTC
**Describe the bug**
Calling `insertOnConflictUpdate()` method throws an exception on Android 10 and below. It works normally on iOS and Android 11, 12.

My solution was using the `insert(...)` method with `mode: InsertMode.insertOrReplace`.

My code:
```dart
Future createOrUpdateEvent(EventDbModel eventDbModel) =>
   into(events).insertOnConflictUpdate(eventDbModel);
```

The exception. The args values were ommited.
```
E/SQLiteLog(27908): (1) near "ON": syntax error
I/flutter (27908): DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT INTO events (id, created_at, updated_at, name, city, state, country, event_start, description, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, created_at = ?, updated_at = ?, name = ?, city = ?, state = ?, country = ?, event_start = ?, description = ?, status = ?) sql 'INSERT INTO events (id, created_at, updated_at, name, city, state, country, event_start, description, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, created_at = ?, updated_at = ?, name = ?, city = ?, state = ?, country = ?, event_start = ?, description = ?, status = ?' args [...]
```

The table:
```dart

@DataClassName("EventDbModel")
class Events extends Table {
  @override
  Set<Column> get primaryKey => {id};

  TextColumn get id => text()();
  ...
}
```

**Comment by kuhnroyal** [comment] 2022-07-15 14:43
Make sure to use the `https://pub.dev/packages/sqlite3_flutter_libs`

**Comment by simolus3** [comment] 2022-07-16 09:57
Yes, please check that you have a dependency on a recent `sqlite3_flutter_libs` in your app. That package is responsible for bundling the latest  `sqlite3` library into your app. Without it, some features that are only available in recent sqlite versions won't work on older Android versions with an old sqlite.

**Comment by daniloapr** [comment] 2022-07-21 01:28
You're right! I just saw that I removed the `sqlite3_flutter_libs` for some reason (it was commented). I'll test it again with the lib.

**Comment by daniloapr** [comment] 2022-07-21 03:23
I believe [this](https://github.com/simolus3/sqlite3.dart/issues/108#issuecomment-1190993742) (or something similar) was the problem that made me stop using the `sqlite3_flutter_libs`.

**Comment by simolus3** [comment] 2022-07-22 10:37
Hm, I think the best course of action is to work out that problem and keep using `sqlite3_flutter_libs`. While the problem is less severe on iOS since more users are running the latest version and Apple ships recent sqlite builds, I think you'd run into the same issue on older iOS versions.

As a temporary workaround, you could add the native dependency to your Gradle buildscript instead of depending on `sqlite3_flutter_libs`. That way, your app will include the latest sqlite3 version without affecting the build behavior on iOS:

```groovy
dependencies {
    implementation 'eu.simonbinder:sqlite3-native-library:3.39.0'
}
```

I'll close this since the original problem is tracked in https://github.com/simolus3/sqlite3.dart/issues/108 already. I hope I can find some time this weekend to debug the build behavior for the SQLite.swift pod.

**Closed as completed by simolus3** 2022-07-22 10:37 UTC
Labels: needs-info

**Comment by zakihou** [comment] 2023-08-01 15:04
iam workin with sqflite: ^2.2.8+4
i have erro in near "ON": syntax error
E/flutter ( 9325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT OR REPLACE INTO paycode

pleass hellp me!!!!
