### ISSUE TITLE
sqlparser error parsing a valid SQL statement

### ISSUE THREAD

**Issue by Lootwig** [simolus3/moor#978] opened 2020-12-19 12:31 UTC
`parse('CREATE TABLE \"sample_table\" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, sample VARCHAR NULL)')`
(called via a test through `migrateAndValidate()`) results in `InvalidStatement`, apparently missing out on the closing parenthesis, causing the validation to fail

**Comment by simolus3** [comment] 2020-12-19 16:39
Thanks for the report. It's actually caused by the `NULL` constraint which tripped up the parser. I can reproduce this with the latest version on pub, but it has already been fixed in 1d7479226a5b578ab0b48646921be8e803480ea6.

**Closed by simolus3** 2020-12-19 16:39 UTC
