### ISSUE TITLE
Option for fully qualified for columns

### ISSUE THREAD

**Issue by North101** [simolus3/moor#287] opened 2019-12-20 14:24 UTC
I have a complex query that has a predicate

```
listCampaignItemBy:
WITH
    list_campaign AS (
        SELECT campaign.id
        FROM campaign
        LEFT JOIN party
            ON party.campaign_id = campaign.id
        LEFT JOIN lineage
            ON lineage.party_id = party.id
        LEFT JOIN lineage_character
            ON lineage_character.lineage_id = lineage.id
        WHERE $predicate
    )

SELECT item.*
FROM item
WHERE item.item_group_id IN (
    SELECT prosperity.unlock_item_group_id
    FROM campaign
    INNER JOIN prosperity_tick
        ON prosperity_tick.id = campaign.prosperity_tick_id
    INNER JOIN prosperity
        ON prosperity.id <= prosperity_tick.prosperity_id
    WHERE campaign.id IN (SELECT id FROM list_campaign)
)

UNION

SELECT item.*
FROM campaign_item
INNER JOIN item
    ON item.id = campaign_item.item_id
WHERE campaign_item.campaign_id IN (SELECT id FROM list_campaign)

ORDER BY $order;
```
(offtopic: good job on having this actually work!)

When building the $predicate
```
db.listCampaignItemBy(db.campaign.id.equals(widget.id))
```

I get an error saying that `id` is ambiguous. I was able to work around it by using a custom expression
```
CustomExpression<String, StringType>('campaign.id').equals(widget.id)
```
but I being able to use the generated column names would be great e.g.
```
db.listCampaignItemBy(db.campaign.id.withTable.equals(widget.id))
```

**Comment by simolus3** [comment] 2019-12-20 16:50
This is a duplicate of #269. I appreciate your contribution, I'll do the necessary work in the generator to detect multiple tables being used.

**Closed by simolus3** 2019-12-20 16:50 UTC
